import Card from "./Card";

/* 홈 화면 */
export default function Home() {
  return (
    <div className="w-[420px] bg-gray-300 mx-auto mt-[100px] p-3 space-y-3 ">
      <Card
        thumbSrc="https://i.ibb.co/Lnwrp7j/Aru-Thumb.webp"
        name="아루"
        nameEn="Aru"
      />
      <Card
        thumbSrc="https://i.ibb.co/QjkX1pr/image.webp"
        name="아루(정월)"
        nameEn="Aru_New"
      />
      <Card
        thumbSrc="https://i.ibb.co/tH43zwQ/Eimi-Thumb.webp"
        name="에이미"
        nameEn="Eimi"
      />
      <Card
        thumbSrc="https://i.ibb.co/FDc15p0/Haruna-Thumb.webp"
        name="하루나"
        nameEn="Haruna"
      />
      <Card
        thumbSrc="https://i.ibb.co/9NkmKVR/Hifumi-Thumb.webp"
        name="히후미"
        nameEn="Hifumi"
      />
      <Card
        thumbSrc="https://i.ibb.co/fdCCbHn/Hoshino-Thumb.webp"
        name="호시노"
        nameEn="Hoshino"
      />
      <Card
        thumbSrc="https://i.ibb.co/Q9BNGDF/Iori-Thumb.webp"
        name="이오리"
        nameEn="Iori"
      />
      <Card
        thumbSrc="https://i.ibb.co/ZXXKntT/Maki-Thumb.webp"
        name="마키"
        nameEn="Maki"
      />
      <Card
        thumbSrc="https://i.ibb.co/wzFJ1Tp/Neru-Thumb.webp"
        name="네루"
        nameEn="Neru"
      />
      <Card
        thumbSrc="https://i.ibb.co/KhvGqsn/Izumi-Thumb.webp"
        name="이즈미"
        nameEn="Izumi"
      />
      <Card
        thumbSrc="https://i.ibb.co/4PCyKtL/Shiroko-Thumb.webp"
        name="시로코"
        nameEn="Shiroko"
      />
      <Card
        thumbSrc="https://i.ibb.co/7WVP2Yr/Shun-Thumb.webp"
        name="슌"
        nameEn="Shun"
      />
      <Card
        thumbSrc="https://i.ibb.co/9YtPs8Z/Sumire-Thumb.webp"
        name="스미레"
        nameEn="Sumire"
      />
      <Card
        thumbSrc="https://i.ibb.co/B6jdFbd/Tsurugi-Thumb.webp"
        name="츠루기"
        nameEn="Tsurugi"
      />
      <Card
        thumbSrc="https://i.ibb.co/wcLj9JK/Akane-Thumb.webp"
        name="아카네"
        nameEn="Akane"
      />
      <Card
        thumbSrc="https://i.ibb.co/j43b6QQ/Chise-Thumb.webp"
        name="치세"
        nameEn="Chise"
      />
      <Card
        thumbSrc="https://i.ibb.co/Lnc7fcL/Akari-Thumb.webp"
        name="아카리"
        nameEn="Akari"
      />
      <Card
        thumbSrc="https://i.ibb.co/p0x90yw/Hasumi-Thumb.webp"
        name="하스미"
        nameEn="Hasumi"
      />
      <Card
        thumbSrc="https://i.ibb.co/mv7BRDd/Nonomi-Thumb.webp"
        name="노노미"
        nameEn="Nonomi"
      />
      <Card
        thumbSrc="https://i.ibb.co/ckfYxjF/Kayoko-Thumb.webp"
        name="카요코"
        nameEn="Kayoko"
      />
    </div>
  );
}
