import Card from "./Card";

/* 홈 화면 */
/* 카드 추가,수정 시 로컬 디비에도 추가하기 */
export default function Home() {
  return (
    <div className="w-[315px] bg-gray-700 mx-auto mt-[70px] p-5 gap-5 grid grid-cols-1 sm:grid-cols-2 sm:w-[635px] md:w-[763px] xl:w-[1024px] xl:grid-cols-3 2xl:grid-cols-4  2xl:w-[1440px] 3xl:w-[1750px] 3xl:grid-cols-5 ">
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1mBgox2qQOXEVmz81fRkGeJHhqrNTj6Cc"
        name="알림말"
        nameEn="Notice"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Ux75KtGG22smCEpEKTcMsRytDUVvsxen"
        name="아루"
        nameEn="Aru"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1KnIQwl5aNJn6cRnVF9w3ZqLyXdrKXRGV"
        name="아루(새해)"
        nameEn="Aru_New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1whUItjsXOBuAkvf-MlcfPC43eIKD5_eQ"
        name="에이미"
        nameEn="Eimi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=19iW0-7gJ5FiraTlSM8vqpOdhYO1ZCXyk"
        name="하루나"
        nameEn="Haruna"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1GB908Sck6rhpB5Jxi2RNb28yGmQ78Qrs"
        name="히후미"
        nameEn="Hifumi"
      />
      {/*       <Card thumbSrc="" name="히나" nameEn="Hina" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1aIN_OOXt23KNUHJK7NMckdprzP6SD5vG"
        name="호시노"
        nameEn="Hoshino"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Ve_BnEs8Geu2b9yxMVu7PpI8qrmxeJZI"
        name="이오리"
        nameEn="Iori"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1b8XJL2hf05uHBcv9inNm8Tuiuva3k7OS"
        name="마키"
        nameEn="Maki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1nRVspQE6arMrVN9bjug3_Y_WO1G8bKkJ"
        name="네루"
        nameEn="Neru"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=18cS-8gczn-sEYKMatQe3yaz1YlQ835xi"
        name="이즈미"
        nameEn="Izumi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1o-1-MK6e_--ItU5E7JwwHeH55uKZcuXN"
        name="시로코"
        nameEn="Shiroko"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1APABgv4oBo9WhpG0co7hrkMF_kVcN1nR"
        name="슌"
        nameEn="Shun"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1feryGg3e6sGKT4iN8v_FbNlrfrFS99bT"
        name="스미레"
        nameEn="Sumire"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1vfI51oA0vFt34mrYyjVkqOCw2GjbIVGt"
        name="츠루기"
        nameEn="Tsurugi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1QehSav2MPe7jYf22PPA1PjWJG-CXdtuq"
        name="아카네"
        nameEn="Akane"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=16CNBn91u_unHuo1rq17PRh3WswlIY-a_"
        name="치세"
        nameEn="Chise"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1hXuHlN5af4M7xQAgdkJIqZ-KaAgHt3l9"
        name="아카리"
        nameEn="Akari"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=10Omz-GH_deku5eQ4SU6t0NGeIaIl4AGa"
        name="하스미"
        nameEn="Hasumi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1X0NITSB6K0d-EHEqxgYcc6hf04g2vXyr"
        name="노노미"
        nameEn="Nonomi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1cR-kWjZaS2fJDKh0shNlK_Ur9tWr2tIX"
        name="카요코"
        nameEn="Kayoko"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1gU5N7DoHGcMpIpIecF7qUjA4srhW1fbb"
        name="무츠키"
        nameEn="Mutsuki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1c4PJ9ttBd4ZcAYEzpDOmBF8sF8l8h_II"
        name="준코"
        nameEn="Junko"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=10A8Fl2qW6FDRywn2qWhNZICPOqQ3PYkO"
        name="세리카"
        nameEn="Serika"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1iNXNGJIdB6zvFADACTG4iXnLVUxdT_Ik"
        name="츠바키"
        nameEn="Tsubaki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1_ak4mA5g0Vh8dn6We0_IqBYP1fRSLWmZ"
        name="유우카"
        nameEn="Yuuka"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=11l8dBGt7xt3FQA1TLgPHqBxUMQrvpcm6"
        name="하루카"
        nameEn="Haruka"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=117JAlzc7SDljtGwCmPzWxXyK5A8EbYyu"
        name="아스나"
        nameEn="Asuna"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1FHkEnrNQTOz7jOz5-c4D9-uFZ_r8cXQ0"
        name="코토리"
        nameEn="Kotori"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=177_weNcx4k4CD7hmlIrPmAoMqfW3xIhv"
        name="스즈미"
        nameEn="Suzumi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1PmpBcznoigoc0wVYiEdEfQmv0D68tQOB"
        name="피나"
        nameEn="Pina"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1eLRJEiN9jcU3BfkYWR6FNOWJGv0WFjUe"
        name="히비키"
        nameEn="Hibiki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1pH3EYelOrWBgpuLACiAVYR7cDP6tIix7"
        name="카린"
        nameEn="Karin"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1-f76N-s1O52m2PLSm0OaeXSd6mmKDyVe"
        name="사야"
        nameEn="Saya"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1en0gWzO86jKSKK80Z3ONAaQrsy4NEr0R"
        name="아이리"
        nameEn="Airi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=121xMFA2GlJQnk9HicerTZ-ig4ieYOn-t"
        name="후우카"
        nameEn="Fuuka"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1kgdLJEF4SWgfpfsGm9rtl60WJgyuZdLQ"
        name="하나에"
        nameEn="Hanae"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=19Z_0aJ6MXKL21ZACnmx_CpQQHiHeEzz0"
        name="하레"
        nameEn="Hare"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1VGw0V8PrvDSZDPgknaV7i6Pz0tmU2tdc"
        name="우타하"
        nameEn="Utaha"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1fPCZjKuS9KiRa_QDT0-0GCXXQURWuLaO"
        name="아야네"
        nameEn="Ayane"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1YsE-sQ6RH6VUZS2khi4-wcz95H2pW3u0"
        name="치나츠"
        nameEn="Chinatsu"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1uV8bPxi8I6fuw1FrqO0Vhpudgqu4hdrS"
        name="코타마"
        nameEn="Kotama"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=15FKiuCxoVJx9lwOF5MeSOIYPnbdomQLS"
        name="주리"
        nameEn="Juri"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1XjXxZmA4PsA-oA76c9wqKMX-U4lzR4R2"
        name="세리나"
        nameEn="Serina"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1PgjyNTwt9OSYTm4nj9STfBvcMCLVlRgv"
        name="시미코"
        nameEn="Shimiko"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1-A-GMgwf9kFaKj3F7Es_HHPvfHZkbAm3"
        name="요시미"
        nameEn="Yoshimi"
      />
      {/*       <Card thumbSrc="" name="마시로" nameEn="Mashiro" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1T2fjYpdbb0kZfjw_E5tGkTE7bMftkxdL"
        name="이즈나"
        nameEn="Izuna"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1drPHDBq1Bb3vaOPGWKRIa0U-PRJ6mBko"
        name="시즈코"
        nameEn="Shizuko"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=17TjcM3-f5H89aN7XKJkCnSdwiwakrYJe"
        name="아리스"
        nameEn="Aris"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=17yXEhSi_u68YRG8pO3tlAjkCBmg7nn-5"
        name="미도리"
        nameEn="Midori"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1PMWPGTab-hfdbNbYYGzhn7TcN29h1vK_"
        name="모모이"
        nameEn="Momoi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1iBqOyKg4bZouL7Xjw9-Yi3UZf7Pd6MhO"
        name="체리노"
        nameEn="Cherino"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1ycgsymIfeRVFBFuLNWWbCcY7QP5cR0EV"
        name="노도카"
        nameEn="Nodoka"
      />
      {/*       <Card thumbSrc="" name="유즈" nameEn="Yuzu" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1MXgFYYBJjAcYkFTolg2zlAcVTVScodQU"
        name="아즈사"
        nameEn="Azusa"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1bov4ukRVxWbxh02FBiRlg4ub47qMNCTq"
        name="하나코"
        nameEn="Hanako"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1JxwidFwG0ehOuLL6M3dvlzvSvbEMbH-L"
        name="코하루"
        nameEn="Koharu"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1CNNNp4s6MxMxPBd69fdZuJ9uEAbIrPPU"
        name="아즈사(수영복)"
        nameEn="Azusa-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Ef2z5sDfKhYScJDe6eq0ukFjyO9eybYh"
        name="마시로(수영복)"
        nameEn="Mashiro-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Ah0NTCUm-1E0xIKdGnHeKZBR7K7dxmPH"
        name="츠루기(수영복)"
        nameEn="Tsurugi-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1A2rUYxp3rGwjJR7PYVMBdXHNC_4vCjvn"
        name="히후미(수영복)"
        nameEn="Hifumi-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=16u98ndd0hU5dD5IwkuaSY8Fb7Q8MYRLA"
        name="히나(수영복)"
        nameEn="Hina-Swim"
      />
      {/*       <Card thumbSrc="" name="이오리(수영복)" nameEn="Iori-Swim" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=18tvrvSUSLLMWO8JA3l8Szcog6ADcYzcs"
        name="이즈미(수영복)"
        nameEn="Izumi-Swim"
      />
      {/*       <Card thumbSrc="" name="시로코(라이딩)" nameEn="Shiroko-Cycling" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=15qfMnIM7lJ6jmhP4Mlg9OvOpeo_4Ok_e"
        name="슌(어린이)"
        nameEn="Shun-Small"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1v4RcyMbC95GiGQolgs8Qn-snztQwisvD"
        name="키리노"
        nameEn="Kirino"
      />
      {/*       <Card thumbSrc="" name="사야(사복)" nameEn="Saya-Casual" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1ZCZexmFyURXob2ZqfdywArZ2aCxUdwBe"
        name="네루(바니걸)"
        nameEn="Neru-Bunny"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1e8rRLfu12VE_ga4CSMzBUAPEvrw7cK73"
        name="카린(바니걸)"
        nameEn="Karin-Bunny"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1D3o_Ibr5-8l1pFG4y6G-s_T33yGrJJyA"
        name="아스나(바니걸)"
        nameEn="Asuna-Bunny"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1829SZ9XcnEvm1ND-oWO8fvHJI00TRDmK"
        name="나츠"
        nameEn="Natsu"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Ez10TfRrTSwht-1yD3rKCO05p6LVXVbH"
        name="마리"
        nameEn="Mari"
      />
      {/*       <Card thumbSrc="" name="하츠네미쿠" nameEn="Hatsune-Miku" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1pNlfqclFZW-8Krs59bb6hjCv7vsS7nlb"
        name="아코"
        nameEn="Ako"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1d9nHnS4XE1AT-RdRSRRTHE82rfhLCd3R"
        name="체리노(온천)"
        nameEn="Cherino-Hot"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=15MKgB_xfEc3a37P4ltGeARsUqZrYaRy-"
        name="치나츠(온천)"
        nameEn="Chinatsu-Hot"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1HmsbUg5UOJ6vwiviHypkI_EovnMyCCmx"
        name="토모에"
        nameEn="Tomoe"
      />
      {/*       <Card thumbSrc="" name="노도카(온천)" nameEn="Nodoka-Hot" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1clhFKnqJK-oFDz_kvLsic_FGIerPyijh"
        name="무츠키(새해)"
        nameEn="Mutsuki-New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1CyHUSMvOKjGspkpMvuGJf_uQHHjhuuG6"
        name="세리카(새해)"
        nameEn="Serika-New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=16AAIAZaoUmudb76ekXFBDxhdOj0RyaaV"
        name="와카모"
        nameEn="Wakamo"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1wZT3ORHMhr2kolq2zP-DutT4wXPafCiq"
        name="후부키"
        nameEn="Fubuki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1LiMucEV4-Ufi8AmtqrEEegZu07Wc3dQs"
        name="세나"
        nameEn="Sena"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1XTZRrXOG-xSN2BSdQUi5FDLre1eBvR-c"
        name="치히로"
        nameEn="Chihiro"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1SfY4HsPNk8Nz7p9EzWYIHR4veU8QvH0T"
        name="미모리"
        nameEn="Mimori"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1QLWH2GsZO408xG5BXN29sM4TlmQminFh"
        name="우이"
        nameEn="Ui"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1VO5UFXHOASaTAHUjn6yyVTOdrawZdgzA"
        name="히나타"
        nameEn="Hinata"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1l0pQY2asuIQEQAyNET4LESUMPKX2Vybx"
        name="마리나"
        nameEn="Marina"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1fEtl9c52Cl02Nqvvo_J4AMfYM7LLUeeV"
        name="미야코"
        nameEn="Miyako"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1z8CJX3jSxADDiPtkmYgyKU8We5eCCYN8"
        name="사키"
        nameEn="Saki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1p5WXbGCsMT41qsAwNg6WR7c6yTEooAp5"
        name="미유"
        nameEn="Miyu"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1A_I0nl2GZXm9sJYiosTjlKR4EjyxukUv"
        name="카에데"
        nameEn="Kaede"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1mXJQSOfLxe5MfXN5ResAjfwTKBiGOFth"
        name="이로하"
        nameEn="Iroha"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1w1vHjYcXxUuiVM40a906125E5Ophc8ml"
        name="미치루"
        nameEn="Michiru"
      />

      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1jDlH_t29H5aKCsQiDrPzw5mZ8SJS27eS"
        name="츠쿠요"
        nameEn="Tsukuyo"
      />
      {/*       <Card thumbSrc="" name="미사키" nameEn="Misaki" /> */}
      {/*       <Card thumbSrc="" name="히요리" nameEn="Hiyori" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Plsg2C5eahxJIJCWlRgKVDdnIhSBKybo"
        name="아츠코"
        nameEn="Atsuko"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=12rLiCfqZMsPOB7YlbK2r95RnfXbVqguV"
        name="와카모(수영복)"
        nameEn="Wakamo-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1edyTp0u6ZBNsOfBKR2EwXyhySS9hRFvL"
        name="노노미(수영복)"
        nameEn="Nonomi-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1UwXKfWPnODTHyk8NAIZc3Ix4akQmj6up"
        name="아야네(수영복)"
        nameEn="Ayane-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1k7Su80TGluiNCXICBumUXvl943SwY1ln"
        name="호시노(수영복)"
        nameEn="Hoshino-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1thgdeJ6S7JXFTWXFkgxTMkaYy-9oL5wv"
        name="시즈코(수영복)"
        nameEn="Shizuko-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1jVOCc1RHEsHS1BPXEfAe5tkTwCRY9U4n"
        name="이즈나(수영복)"
        nameEn="Izuna-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1vqRsZSsqV3EjpnTJC7Jbbc71d4qdK75Z"
        name="치세(수영복)"
        nameEn="Chise-Swim"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1WWeXuBlR633cugf2HA-3ZgmQT1CGQxOr"
        name="사오리"
        nameEn="Saori"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1MRigi7ECaYUylyFnPDqO7TxorIcK0Is3"
        name="모에"
        nameEn="Moe"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1J94WMouHKvalAP2Fr_HqPkCY8GZP6VyW"
        name="카즈사"
        nameEn="Kazusa"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1-rwllWoLj58S3fzYzEnJWbpRno6DRE7o"
        name="코코나"
        nameEn="Kokona"
      />
      {/*       <Card thumbSrc="" name="우타하(응원단)" nameEn="Utaha-Cheer" /> */}
      {/*       <Card thumbSrc="" name="노아" nameEn="Noa" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=12tU8x-XLqPhxHHFiKjOH5NkciAA_stZi"
        name="히비키(응원단)"
        nameEn="Hibiki-Cheer"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1SvxaUyWXZ7g1l8Jt3HbriGCGJb7fcCFW"
        name="아카네(바니걸)"
        nameEn="Akane-Bunny"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=17SPpqy_kLTKJmDN1fLpHGde9fh9pVD9J"
        name="유우카(체육복)"
        nameEn="Yuuka-Track"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1HtunahoA8KPn5lgyF1TuhhB4bd7kJnzm"
        name="마리(체육복)"
        nameEn="Mari-Track"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1hA33W42rhh3k2RF0PVMF94gSm-QES9Jv"
        name="하스미(체육복)"
        nameEn="Hasumi-Track"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1uVv--b7Jw2ILrbhvUwAo2NzTqm904E_e"
        name="히마리"
        nameEn="Himari"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1O5BIOzS96d9QycKoLC7Ryfs45wxOerQM"
        name="시구레"
        nameEn="Shigure"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1FiwdiD3SJK5FwLhavebh18k7TZUBC62y"
        name="세리나(크리스마스)"
        nameEn="Serina-Christmas"
      />
      {/*       <Card thumbSrc="" name="하나에(크리스마스)" nameEn="Hanae-Christmas" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1CgWwLENzXbrcD04oApA8iSDFMm0K9vua"
        name="하루나(새해)"
        nameEn="Haruna-New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1vKMOpta4RgyBONnRJNsT3A5-j2gx9DS1"
        name="후우카(새해)"
        nameEn="Fuuka-New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1xlf92f-098iub4PXqM99QahVIc0aeQ_f"
        name="준코(새해)"
        nameEn="Junko-New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1qgg0-arUuSBll99EhjPHvy0fvQIffXZx"
        name="미네"
        nameEn="Mine"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1tKFZYtfpfl_1sNRQ0Y2CdEXG5l6IUFuz"
        name="미카"
        nameEn="Mika"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1Lu5sNw04Om-5Nah1865iaU814DVCQvVN"
        name="메구"
        nameEn="Megu"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1MI8ZYwV-HHYy_BrT68MNo7_Rr9-Hgu3R"
        name="칸나"
        nameEn="Kanna"
      />
      {/*       <Card thumbSrc="" name="사쿠라코" nameEn="Sakurako" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1F6ZGO4cMaY_diQhLTcqI1kucXT3XhSg0"
        name="토키"
        nameEn="Toki"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=14hBqW8FtXX-v2kIBFl8wS2Z8C6nv5aXj"
        name="나기사"
        nameEn="Nagisa"
      />
      {/*       <Card thumbSrc="" name="코유키" nameEn="Koyuki" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1FQG2_Qe-bWv_CP61N2S1Pp839Si0cmLM"
        name="카요코(새해)"
        nameEn="Kayoko-New"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1j7E1wa1UD07V3ppEu2UFGl9J185mmPNP"
        name="하루카(새해)"
        nameEn="Haruka-New"
      />
      {/*       <Card thumbSrc="" name="카호" nameEn="Kaho" /> */}
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1b-6njO9eX7dciW85E89RfzmSBgkAUj3e"
        name="아리스(메이드)"
        nameEn="Aris-Maid"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=15MuBwjclhd4TbDCjfbPkgwBsexjl3Opa"
        name="토키(바니걸)"
        nameEn="Toki-Bunny"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1GGwBsguLqOFBwtIQGaAmgr80K8aLPM7b"
        name="유즈(메이드)"
        nameEn="Yuzu-Maid"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1jUJtSrJX7LbYSWip5P7ktqXJ0GVZ7A9D"
        name="레이사"
        nameEn="Reisa"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=1_WJrKYDH8KRTDey_Dmp2bzz0fLRJeEXQ"
        name="루미"
        nameEn="Rumi"
      />
      <Card
        thumbSrc="https://drive.google.com/uc?export=view&id=16fzkVvjpMkLnQ6s5tDCoRgiMYHqLyytn"
        name="미나"
        nameEn="Mina"
      />
    </div>
  );
}

/* 카드 추가,수정 시 로컬 디비에도 추가하기 */
