export const localDB41_60 = [
  {
    _id: { $oid: "656fd9346a3dd9a4271f5e1e" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=10ba0RDfdzSzhB3qdtjqucYYJaIE7bTBV",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Chinatsu",
    Kname: "치나츠",
    Ns: "",
  },
  {
    _id: { $oid: "656fdbbe91e2a179d0691a30" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1xIgLv3qca81H79t4fwOh7m90SfF1JXmk",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=11RETNb3MGN0rlVQ9M0UoYiHWXQk2Lp_0",
    Cafe2: "",
    ExReload: "",
    Name: "Kotama",
    Kname: "코타마",
    Ns: "",
  },
  {
    _id: { $oid: "656fdcb591e2a179d0691a31" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=119oxAwD1C3Ni0ybx_xZ40JBrSlVEyL2S",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Juri",
    Kname: "주리",
    Ns: "",
  },
  {
    _id: { $oid: "656fddbe91e2a179d0691a32" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1qHmTxaZaEN2D_v7Y92Y_RLft2HKLPgy3",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1vs3VxPGxjvNrzzCGY5bd8aKNULhPldgd",
    Cafe2: "",
    ExReload: "",
    Name: "Serina",
    Kname: "세리나",
    Ns: "",
  },
  {
    _id: { $oid: "656fdf0591e2a179d0691a33" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1GILtcLt56usjGcQxqGu059mwwKmdK0Xi",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=14upsnrHQY3mIK5UolPOjLBbkOh1dmSHI",
    Cafe2: "",
    ExReload: "",
    Name: "Shimiko",
    Kname: "시미코",
    Ns: "",
  },
  {
    _id: { $oid: "656fe00591e2a179d0691a34" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1-0cyeGc5Lre3MZgoYUNFMpwBR_KGcRnn",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1sIo-hA0ED7nPfrsGZlrJp0VulTZD8Dz8",
    Cafe2: "",
    ExReload: "",
    Name: "Yoshimi",
    Kname: "요시미",
    Ns: "",
  },
  {
    _id: { $oid: "656fea1c91e2a179d0691a35" },
    Win: "https://drive.google.com/uc?export=view&id=1X_-HVsdMaj9c5P7ZA3lYwNl9St089KXh",
    Start:
      "https://drive.google.com/uc?export=view&id=1_OaXEyJcLfNRR2vei-r9aIm4y7TQor8Z",
    Reload:
      "https://drive.google.com/uc?export=view&id=1D_V9aF1czA3zHwknLnA7TCykCUWcDqoc",
    Ex: "https://drive.google.com/uc?export=view&id=1MRc8WFC6Sd58VJnZ6B6c6oJVAZ2zueZI",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1DZQvUbgdOasL8eqSJuRAs774KzCcYgOH",
    Pick: "https://drive.google.com/uc?export=view&id=1wi9OI8bqi4BIMpwE-t0GAhZDmJqqHpm1",
    Hide: "https://drive.google.com/uc?export=view&id=1H96Rh0_l1k_OrcWRaQ9Kd45brDtCm9bt",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1O5oRp8MWp3h8n5184d8oIPtEiN22uCcd",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1PuhzMIOhMgYnHQ0Y_G5Xv5H8UGdLcn8l",
    Object:
      "https://drive.google.com/uc?export=view&id=1P5jxcQFL189QEGABazIP0-3AUAOzxQcP",
    Cafe: "https://drive.google.com/uc?export=view&id=1edUiqzwUCKj8wiJfQZwRAlUJxrvHlNUX",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1wmqg9DRGNe2SCNdoHnKzvv9SjfCEv-xL",
    ExReload: "",
    Name: "Izuna",
    Kname: "이즈나",
    Ns: "https://drive.google.com/uc?export=view&id=1eVecK5ECpRIwFT9fBqQRFVDL42nov6fY",
  },
  {
    _id: { $oid: "656feb8091e2a179d0691a36" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1kWzxB2L9s_Me98YbLephw5cbmK_2aH7A",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Shizuko",
    Kname: "시즈코",
    Ns: "",
  },
  {
    _id: { $oid: "656ff6aad38f394f005edc38" },
    Win: "https://drive.google.com/uc?export=view&id=1Q3j_YSY07CX0J127jr6Xu8Bha8S4H8El",
    Start:
      "https://drive.google.com/uc?export=view&id=1cko5bfLV6qv7LaK7qLvQQb6hoEGcGXRS",
    Reload:
      "https://drive.google.com/uc?export=view&id=19TutuatubredQnZs-33AvSTc_37ksvr4",
    Ex: "https://drive.google.com/uc?export=view&id=1wzLcJGSlY9KFGcJcnGJsOuSPhzp5f076",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1vzKRqUjT6AMtOZhJdhXvOMrk93Z1_8i6",
    Pick: "https://drive.google.com/uc?export=view&id=1BNxm4_QhQLUTZ8FEF6RfO8BQ7czMFTPL",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1Fnq6NKKxorzWaY0DjfztHNCEkAJTougq",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1J_A3slD40sd7HcopJlIiKdS3zeTyrECJ",
    Cafe3:
      "https://drive.google.com/uc?export=view&id=1-yYvkkFZ9PSqLq2sp6zIeKE1dn-Ry5nW",
    ExReload: "",
    Name: "Aris",
    Kname: "아리스",
    Ns: "https://drive.google.com/uc?export=view&id=1iaeY8T8adbz6Vf7bZvJj-hCjsEoyCJGp",
  },
  {
    _id: { $oid: "657052cb755483fff5891a7e" },
    Win: "https://drive.google.com/uc?export=view&id=1hTYXqvZhP0I1VGbXwTQtZ1hvmUAbRVfE",
    Start:
      "https://drive.google.com/uc?export=view&id=1Q8oV2IJp97BJXrWLFKqESjdE7FfVzuMy",
    Reload:
      "https://drive.google.com/uc?export=view&id=1aHKaVw1O7SaJbwYvO6yNMRW5Di2bL1ym",
    Ex: "https://drive.google.com/uc?export=view&id=1IJC7sAtk9plHcIclSM5inNhwpZtxnjxZ",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1mrZMnL3TtBIZ-7XK7NoflRmK5NV9KZCi",
    Pick: "https://drive.google.com/uc?export=view&id=1GW5zykHFlM2B2HrBggkqcG0AAaBtyM9p",
    Hide: "https://drive.google.com/uc?export=view&id=1Fs1-0dvt9S5v99xVPEAV0urNskVrLXaS",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1JpEJIqVx7jtB7zmDxwxAirpPv230wFn_",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1oSTefequtb4fTuoqIcXMwqKoWoSbIrr5",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=178Z_MmXNI5TBjRhfknlmBlUfAUFAczKr",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1XBFHFUIIIssxAkDLEjATqUDkmZ6fbHp8",
    ExReload: "",
    Name: "Midori",
    Kname: "미도리",
    Ns: "https://drive.google.com/uc?export=view&id=1IcGYYAyaiEzvgX9uTRZhE4bLi6CbT2yR",
  },
  {
    _id: { $oid: "65705935755483fff5891a7f" },
    Win: "https://drive.google.com/uc?export=view&id=1kywcJq7QudwK-NIl-bU1WsMj2yw-Atm8",
    Start:
      "https://drive.google.com/uc?export=view&id=1enXdnPwxPOMq0kJoswrRc2ylV4-8fONf",
    Reload:
      "https://drive.google.com/uc?export=view&id=18WeApZk00B6QHseLAdLf-wumEqs-503L",
    Ex: "https://drive.google.com/uc?export=view&id=1QVVL3-z54g7iz7apQCqhrWYE0z40Ebo9",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1tYwjmSRmJabeYUP9oqYqrwa3IRsuwRXJ",
    Pick: "https://drive.google.com/uc?export=view&id=1wazxKH3nG1_PcoMQm4JtTSxvoOUO123X",
    Hide: "https://drive.google.com/uc?export=view&id=1NpzE0v0FsoP6i7jkMm1OGYLw0c3ayKSs",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1sbk_Cg7meDjNXvT92ZEl6NC0g2BjCA6_",
    HideReload:
      "https://drive.google.com/uc?export=view&id=13OQUlFupOl3yF689qK-EqjiB6nc8thBB",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1IOoVGfY6qKs1gccq6W4U7MSs-g3kSW10",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1-xUKlUshG6qxxU32mhuTl9AeUkcNQJG9",
    ExReload: "",
    Name: "Momoi",
    Kname: "모모이",
    Ns: "https://drive.google.com/uc?export=view&id=1KODVHncAdmMM_2TdyOveShmFHySKu-oT",
  },
  {
    _id: { $oid: "6570606a755483fff5891a80" },
    Win: "https://drive.google.com/uc?export=view&id=1hR0sBtalJEReGKTT3XZCvM9zcbRN0b_p",
    Start:
      "https://drive.google.com/uc?export=view&id=1Eh3GE9FCkvR6X5gNoUDdmtA2oOwMA59Y",
    Reload:
      "https://drive.google.com/uc?export=view&id=1TC7Uhg9deIanidkTca9nR3qmzUZ3TYKU",
    Ex: "https://drive.google.com/uc?export=view&id=1sUrgGoajiEPV2GvBycMNmS-WCPw_WbZl",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1MrtAPE47jDvoKTDlebUy2-vkhpaR0xf_",
    Pick: "https://drive.google.com/uc?export=view&id=1gAkjswVSEb4yzizCWNoybELJWJq8jVAR",
    Hide: "https://drive.google.com/uc?export=view&id=1wbe9w2soPzzg2J3LzvoKOnvMLjd55qcC",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1pC3BxBD8ORkUUMXBPHdcpQfhfyMP7lf0",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1p3uuflc2TBVkEpHctD2u0jon3psFWCcb",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1E0Prh5Z9ZmSt5tWtc1-qVGrkfgJzJDkp",
    Cafe2: "",
    ExReload: "",
    Name: "Cherino",
    Kname: "체리노",
    Ns: "https://drive.google.com/uc?export=view&id=1llL4dEzDxULcpy07EfIPodEqVM7T0b40",
  },
  {
    _id: { $oid: "6570620d755483fff5891a81" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1pl1DgqQxx-BX1UgXiUF0lkYzkbjJEYm5",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=19A2-jehXJ6KAEgwzL6xKduhn1bXe4uV1",
    Cafe2: "",
    ExReload: "",
    Name: "Nodoka",
    Kname: "노도카",
    Ns: "",
  },
  {
    _id: { $oid: "657087957399f4f142da3251" },
    Win: "https://drive.google.com/uc?export=view&id=16P-m2NVOmDJyt9lXSi42d7wRjrYKK70p",
    Start:
      "https://drive.google.com/uc?export=view&id=1IR8EStie89JsnZ1cI_Dvk3yLdvuNWZ2M",
    Reload:
      "https://drive.google.com/uc?export=view&id=1ccXJKtI5itc8MJShVlNNZW3YYhEmH0Hw",
    Ex: "https://drive.google.com/uc?export=view&id=1A_3DrZj-j7essRneRrKd6oUAJb1_HIAO",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1A-qDg0v-uE3Akc-cAfbFEZS-CSWiwlj2",
    Pick: "https://drive.google.com/uc?export=view&id=1hEzUbiFS-HSh-SvcmcO5ltqAuBJFDv4E",
    Hide: "https://drive.google.com/uc?export=view&id=1AW12AE1L7Dm9liuyVdWegG_7kG9FufNm",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1EQxoisVYsan4836RMWMn8CGT-Q1WEBQC",
    HideReload:
      "https://drive.google.com/uc?export=view&id=18sqWZIhiUfcMXEZsgiSMTnQxB7LQ346-",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Azusa",
    Kname: "아즈사",
    Ns: "https://drive.google.com/uc?export=view&id=1xQ2h44Rf1_XTZr7D87Zf5VFDwnHoNdT2",
  },
  {
    _id: { $oid: "6570890d7399f4f142da3252" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1qM_F2qRoU8fmq-qb8QQOURhRRlQ2jSw1",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Hanako",
    Kname: "하나코",
    Ns: "",
  },
  {
    _id: { $oid: "65708e277399f4f142da3253" },
    Win: "https://drive.google.com/uc?export=view&id=1ha_qQOgnNKZJi5w2nKyUY0NbtFSWOXZf",
    Start:
      "https://drive.google.com/uc?export=view&id=1Qhhl5SGhp5tSd356Ky1Ycd5zsx4suv8r",
    Reload:
      "https://drive.google.com/uc?export=view&id=1qOHNM6Espig_VoKBhzx1_aV0_h-AZgB5",
    Ex: "https://drive.google.com/uc?export=view&id=1LtEpM2y1aW9o09BFTzGMhERfZ7w94lLz",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1hfkicYkXrqV3yWMSrg-ezJc5MOJoPbgZ",
    Pick: "https://drive.google.com/uc?export=view&id=168K_IK-Q2uMD70zu_SwEZXGuQBTQEnfC",
    Hide: "https://drive.google.com/uc?export=view&id=1S94VIC4dqfSiDDRDeTmLTbvRvIuD0inO",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1Ewi_DLKFYzobuGouepRXxnMDHlXXlPvh",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1DSZI-FekjW31-yTVceyknX9ZaZV3fFNB",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Azusa-Swim",
    Kname: "아즈사(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1YVFwieQMSvchQqgBCebhNnucYkk0ywl4",
  },
  {
    _id: { $oid: "65712b1df49ec7a955d6fa5a" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1kH6wAxnMqQtEwceldVHnhGtR4hajvgU4",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Mashiro-Swim",
    Kname: "마시로(수영복)",
    Ns: "",
  },
  {
    _id: { $oid: "6571317404ed1e7ab9e5f080" },
    Win: "https://drive.google.com/uc?export=view&id=1qFp794j-Wzecun39JBjcOlQGCVD-9ue_",
    Start:
      "https://drive.google.com/uc?export=view&id=1u-rdBPu_hpiaItO2AIGAKO9wYYusuKFv",
    Reload:
      "https://drive.google.com/uc?export=view&id=1zpd_k_hPh9wZ72Sw595MeMslctsVpONx",
    Ex: "https://drive.google.com/uc?export=view&id=1q6tsdTQCfIPjqjknAcDCXIpo3cQx5sLX",
    ExAttack:
      "https://drive.google.com/uc?export=view&id=1A41JhG_CEX4YF_OLZBbqTl-PuI6mRToz",
    Attack:
      "https://drive.google.com/uc?export=view&id=1gbRq4OC_q1fdV4HZErDhDwgDExc2oyu6",
    Pick: "https://drive.google.com/uc?export=view&id=1xndc0C8nGlm_-MhTpCsvo6MuVKJQ5JqB",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload:
      "https://drive.google.com/uc?export=view&id=1XOoVGcdjJwBPkP45T1r6qqmJF0b4ABeV",
    Name: "Tsurugi-Swim",
    Kname: "츠루기(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1SQXZJFC-U2xf_Y0XOHFHPW74S5u-gyYo",
  },
  {
    _id: { $oid: "657135cf04ed1e7ab9e5f081" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=14mFLMa5r16T4-_oyGHDMryOmyxZ3pj1g",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1mO0UyO_0qgulc7-i453WNmHHY_frrS5q",
    ExAttack:
      "https://drive.google.com/uc?export=view&id=1vjnhTnA6JCuWmTY5bsU4LT17LzeIfhsw",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1I0yBqmXScea_LbkKofkgFUGoijR_gdGs",
    Cafe2: "",
    ExReload:
      "https://drive.google.com/uc?export=view&id=13sGOOOZqlv275ZRxXfghVpGzJs0Rpgav",
    Name: "Hifumi-Swim",
    Kname: "히후미(수영복)",
    Ns: "",
    ExNs: "https://drive.google.com/uc?export=view&id=1U1joNgFK6ohfTIIb7i3Hdg6IwMlgEDe-",
  },
  {
    _id: { $oid: "6571777ee424c7d047609559" },
    Win: "https://drive.google.com/uc?export=view&id=1jIaFLnNuC9XHUCS8sEbNl0G_026q6yYb",
    Start:
      "https://drive.google.com/uc?export=view&id=1rhK3iBzrs6D8dkPchzlib9cdkq_4qMLE",
    Reload:
      "https://drive.google.com/uc?export=view&id=1aN2EKplnoSPDOYgXfuE3rM0MPIyZNGjG",
    Reload2:
      "https://drive.google.com/uc?export=view&id=1OFvqSuUCoobQ6be5kdwNqVkB3fBpToH2",
    Ex: "https://drive.google.com/uc?export=view&id=1Ho9t4XQynq7eSXaQlkmHWhezUAjNVl02",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1TO-nrD4i4SyNTLk2IJuN7Pj6o-neqWNZ",
    Pick: "https://drive.google.com/uc?export=view&id=1ZuJ-tArZx9c_5l7L1r_tx0NYaez5PNbj",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1RWAedWeSCzDX6Dt9p1pYoNrsLKH0w_X-",
    Cafe2: "",
    ExReload: "",
    Name: "Izumi-Swim",
    Kname: "이즈미(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1zfLb_UwTsuoVq-bsNt6w_2xni1HaHt_Z",
  },
];
