export const localDB141_160 = [
  {
    Win: "",
    Win2: "",
    Start: "",
    Start2: "",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1xF2GrqK-qEzRh9PTgeBJuQXS2heNjtIu",
    Cafe3: "",
    Cafe2Webm:
      "https://drive.google.com/uc?export=view&id=1_SGOwBiCIB219ZBf72SE3cEfpV_DlW-2",
    Ex: "",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Name: "Yuzu",
    Kname: "유즈",
  },
  {
    Win: "https://drive.google.com/uc?export=view&id=1cakTsbC9E_scqlyzXjelh1ZQ9KXxuqh6",
    Win2: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1aRxVf1m8u7UwmD9IgdzIHbKbKS1jibFv",
    Start2: "",
    Reload:
      "https://drive.google.com/uc?export=view&id=196mBZiMxSS4bN7giX_CQcLS3U_Wzi5B2",
    Reload2: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1GepYJyAuNmKO_w27hebGMeobFATxdxWN",
    Ns: "https://drive.google.com/uc?export=view&id=1PNn3zvjT8lOdwJlxCe3DOHhI_1OdTLyS",
    Pick: "https://drive.google.com/uc?export=view&id=1m7QjRDT4UtUOpfXYUnrr0SJJgN9gLPvX",
    Object: "",
    Cafe: "",
    Cafe2Webm: "",
    Cafe3Webm: "",
    Ex: "https://drive.google.com/uc?export=view&id=1X9uX8X_rTWbRMZsZzU6ZtTY20N4CEu9S",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "https://drive.google.com/uc?export=view&id=1YDADiATdP8oazSpzYRMARNWeYIe7E1Mi",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1gjXk_NHMimxwpxaV5L5bV-BLVeRDWdcC",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1k_vf23PAuIjRTh92ysEVBmK090ZpeGiy",
    HideReload2: "",
    Event:
      "https://drive.google.com/uc?export=view&id=1asEf20SndABSzhcYCKN4NvbOTYHPAI62",
    Name: "Miyako-Swim",
    Kname: "미야코(수영복)",
  },
  {
    Win: "https://drive.google.com/uc?export=view&id=1ITrSEBy36wlAWHecS_B0-xJhqfXkg_mv",
    Win2: "",
    Start: "",
    Start2: "",
    Reload:
      "https://drive.google.com/uc?export=view&id=1qf0QIoaOe9fWWP4HXXKgPk78iIy6ECpc",
    Reload2: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1BeKxQLH8Ehkl8cOvmTbBJr0BaVv8KOAb",
    Ns: "https://drive.google.com/uc?export=view&id=1iU0GFUEoNLAXA6xP53nqkpw0Pes5LkWa",
    Pick: "https://drive.google.com/uc?export=view&id=1n4pgskiRMurGomvJrFOB4r_iHWFsJ0dV",
    Object: "",
    Cafe: "",
    Cafe2Webm: "",
    Cafe3Webm: "",
    Ex: "https://drive.google.com/uc?export=view&id=1PGzqaxpJcral0EcncojBlYOm1r3QOgwR",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Event:
      "https://drive.google.com/uc?export=view&id=1gA6j_FRMRd6Jow56eUwwexWgD_hh0GHa",
    Name: "Saki-Swim",
    Kname: "사키(수영복)",
  },
  {
    Win: "",
    Win2: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1ZtBUkfDGfxbCTmYBb7C7phGY6-GgraJ6",
    Start2:
      "https://drive.google.com/uc?export=view&id=1InfDKA-s-Owfe_SxA_TX9EZC8SZo2uqm",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1vUxinMlFE80TqRaWHswoC39czMw5hAqJ",
    Cafe2Webm:
      "https://drive.google.com/uc?export=view&id=1Riq4VUJQilPvi8OlzCn2ijvD4huDpYpG",
    Cafe3Webm: "",
    Ex: "https://drive.google.com/uc?export=view&id=1elMsMFdbUs_I-78cY0msqmERryq6s3WF",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Event:
      "https://drive.google.com/uc?export=view&id=1rlTuEX72VEDSrvGgOxCWkvCA2--Iingn",
    Name: "Miyu-Swim",
    Kname: "미유(수영복)",
  },
];
