export const localDB141_160 = [
  {
    Win: "",
    Win2: "",
    Start: "",
    Start2: "",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    Cafe3: "",
    Ex: "",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Name: "영어이름 이격은 aaa-Swim 으로 표기",
    Kname: "한국 이름 세리나(크리스마스) 표기",
  },
];
