export const localDB81_100 = [
  {
    _id: { $oid: "6573159fd33ff1caa12e02dc" },
    Win: "https://drive.google.com/uc?export=view&id=1mF1RAI3DcdFqD1oNsep4M7sJ-xHJuZAO",
    Start:
      "https://drive.google.com/uc?export=view&id=1pXQ_8pdInann6S7u5A_BOI5FwY5bLE9K",
    Reload:
      "https://drive.google.com/uc?export=view&id=1pO5S5ZfZxoNxmjmat-5F61IOsbMeyMkV",
    Ex: "https://drive.google.com/uc?export=view&id=1LSfk2dPZiGMkfipARcxYYQHMCcwBuEXZ",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=16AkXHy7XN3gwCsf-5e6WM6fVIz-sVB7e",
    Pick: "https://drive.google.com/uc?export=view&id=1KWPP1sIIxc2V4TYGLGAxIe04e-8lSAX5",
    Hide: "https://drive.google.com/uc?export=view&id=16PPKbqn0SeL9aiVNSA6FGqdqCcehR_89",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1RV_hIluLEaKLHENmljcPJuUUHow9cyl_",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1GciBKIyjAK-scFA74KnVvdec2tWvZWqx",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1OZTw9FYCIXr68keTt0XeadkfG7GYQVRN",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=15icI8FUSK8HM-h7mq4ixdwN_mENyaH66",
    ExReload: "",
    Name: "Hinata",
    Kname: "히나타",
    Ns: "https://drive.google.com/uc?export=view&id=1BDwCtHUs9byKaDt2fzWGjDbFWfe89akq",
  },
  {
    _id: { $oid: "65731bca17875d7e367181a8" },
    Win: "https://drive.google.com/uc?export=view&id=1acQW6hmC_iO538XN5E3sTgPExVX3nP-f",
    Start:
      "https://drive.google.com/uc?export=view&id=16hhZRbXMW6wsawk7wlpS-pU4bMiuhiEH",
    Reload:
      "https://drive.google.com/uc?export=view&id=1sZVOsK-khPauudls7gGkDpCLlycJ9uIN",
    Ex: "https://drive.google.com/uc?export=view&id=1KzTRxZBMlqkfxAZpS-FXxF7CeUqkbY23",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1DPO75kMj0vu_icoZgem4TQDHfO4miqV-",
    Pick: "https://drive.google.com/uc?export=view&id=1hfV7GzZqby-YZSyS9sHPPPjWOIIW4pP8",
    Hide: "https://drive.google.com/uc?export=view&id=1aB8cfHa6QsbOFEBuWVByrERnY1MIaUIp",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1cZ1GRwJq1DEqkhzS58WU8ykgGgsPTRIr",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1fipDxKt_dq0rBup-ay74kbj2vWGblRGu",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=16g5d3B3rk9N7z73-Nub7d2Uty47ilbuC",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1Qf3NZW379KKjrNSCeAsom9PlU3Gwzvkb",
    ExReload: "",
    Name: "Marina",
    Kname: "마리나",
    Ns: "https://drive.google.com/uc?export=view&id=1LUbFn9BlHtfMVJ2X4OZJvcNS2IAn-ZgI",
  },
  {
    _id: { $oid: "6573217117875d7e367181a9" },
    Win: "https://drive.google.com/uc?export=view&id=18SoHpEaaG2TavqdzIviC_65LdW1-pz83",
    Start:
      "https://drive.google.com/uc?export=view&id=1CtPOn4M9AjRULH41UiKpDlGUQLAhPMIR",
    Reload:
      "https://drive.google.com/uc?export=view&id=1kykuXm-3NDIPFoYRBZZW-JJxWXnG4bk6",
    Ex: "https://drive.google.com/uc?export=view&id=1OIriw1rQPUhrqrL3GZ5u9jOAzutLoZ6b",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1VA-EK97NvZ6Rz0T2xDS0Y4_shEh-Ra10",
    Pick: "https://drive.google.com/uc?export=view&id=1QQc9xrXmIfmDAwuvYwuNjF5Ao-soRRBh",
    Hide: "https://drive.google.com/uc?export=view&id=1eEjMcRbTimeXYOB-5IGWN17vFP_gZDn4",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1vSuB0jOIhjzY23hBhT4201WHwBfDtiZq",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1r0VsMwU6aAnEVGKXPcFr_Zoejcra2Dfz",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=11FdrMI4Sal7qZ5tFJMNGD4EAstqnTeL3",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1QE_hkuJ8rjpSBgxvxneCtK-vG0c9VmlT",
    ExReload: "",
    Name: "Miyako",
    Kname: "미야코",
    Ns: "https://drive.google.com/uc?export=view&id=1Gj6fMSLOENGCWns8Pvkhzl_JxJx7mxBd",
  },
  {
    _id: { $oid: "6573238f17875d7e367181aa" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1xoEiNvVw2JEpspoHb22gSfenfxcW_vUD",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1v7Kh7V-1LLeA7EI0zdKUFXqK-JTRycHw",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=18fJ78jf-quFXn81ol0QtLmcGfceSB_TU",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1wxfXSgkCW-J2QLaRekn4K72PvfkJK4T3",
    ExReload: "",
    Name: "Saki",
    Kname: "사키",
    Ns: "",
  },
  {
    _id: { $oid: "6573278717875d7e367181ab" },
    Win: "https://drive.google.com/uc?export=view&id=1kDp9cqX21dfDGHOGD5nbPFh7ojp2P5XO",
    Start:
      "https://drive.google.com/uc?export=view&id=1JSVAL5GndYKmCY16els_KQehC7zZd_C0",
    Reload:
      "https://drive.google.com/uc?export=view&id=16xyrubV37jvx8G-Ug30E26P9PGy3WQT9",
    Ex: "https://drive.google.com/uc?export=view&id=1BtT-pf_obzzUbo6J_jR_PXn2VHpUea-K",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1mqpiEqb9-iBuodLLM8EikjFJ4n0UAmFF",
    Pick: "https://drive.google.com/uc?export=view&id=1t4U1j9G4v5NwIyJu4z4l1MBrjGbW7kan",
    Hide: "https://drive.google.com/uc?export=view&id=1mcYNWDYyOIcqgfmjskL08gq_qzvNDGq4",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=18-RCmR7_z0tJu-tUr6btgn0QyPUyLY77",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1iOK6Lftkn2wvsqZVSJAoe_0TLc_xrydI",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1VhK8ZKmI_DqBmZkhRE4m72ratiy7nkTO",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1VuzuQhsX-EusC44cZZ0UwadMWQzDriM6",
    ExReload: "",
    Name: "Miyu",
    Kname: "미유",
    Ns: "https://drive.google.com/uc?export=view&id=1j1o7YiUvpiorbbY0Mo-FD0-Nux3QAba9",
  },
  {
    _id: { $oid: "657328f217875d7e367181ac" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=11oUKGNcmF0gQByRV08EZQlwpv7GVNmTg",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Kaede",
    Kname: "카에데",
    Ns: "",
  },
  {
    _id: { $oid: "65732bdd17875d7e367181ad" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1H72xKJQU1WeI3OLyLzsGCvJcBZU9cCzX",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1qqJE_NvQD0N0IJp2DtVrGw5crVxrC2Cg",
    ExAttack:
      "https://drive.google.com/uc?export=view&id=1VRTFv-ZKBcxpa-w4RhMofbMOOEJCUQru",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload:
      "https://drive.google.com/uc?export=view&id=1qpq2H6JzqsxxSNwk6-EUv0h6bjGrcH3G",
    Name: "Iroha",
    Kname: "이로하",
    Ns: "",
    ExNs: "https://drive.google.com/uc?export=view&id=1jt5yR8IbCI0IbCytHlhOZN-K4Mdkz4J9",
  },
  {
    _id: { $oid: "6575d0fb9ce88162e5f127f8" },
    Win: "https://drive.google.com/uc?export=view&id=1tlsjGlpuHjKCWODUlRwpDVs90NY2pmIp",
    Start:
      "https://drive.google.com/uc?export=view&id=179k0fpErgibh_ALZPMMUNsXBHrcJG_QJ",
    Reload:
      "https://drive.google.com/uc?export=view&id=1Syja3sCHquNMYGP5Yt99iYHMAq8HUJok",
    Ex: "https://drive.google.com/uc?export=view&id=1xO7U2_uEpVczDn2u1VAb1JoKqU4qqoLN",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1RYQlPPJI7cII8maxM9CA75g8Kowonrdb",
    Pick: "https://drive.google.com/uc?export=view&id=1hQroxdrexKzEvpugEA9xxr_pWXxnCMtL",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object:
      "https://drive.google.com/uc?export=view&id=1W5VFzwtvczwIy4AccdQfpwefUPSBdktq",
    Cafe: "https://drive.google.com/uc?export=view&id=1EjkCX7GaEEiVC-gMeH07mJcvLyQLewHL",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1kxyGVDbzxe9KkWlP21u1ONvMAnveoS_T",
    ExReload: "",
    Name: "Michiru",
    Kname: "미치루",
    Ns: "https://drive.google.com/uc?export=view&id=19m1QujCBrQ_dpWol4UN8rQb7Z2INaTig",
    ExNs: "",
    HideReload2: "",
    Reload2:
      "https://drive.google.com/uc?export=view&id=1yg1WwLzyFLkinT6N7cvq1Av4fmHITY8D",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d18134a0b108b32cf2aa" },
    Win: "https://drive.google.com/uc?export=view&id=1VdcYK0oK0-sdm2eu1QL0fCtiWfh1wObr",
    Start:
      "https://drive.google.com/uc?export=view&id=12bWnQ3BAXep1ppOxLw9A-xHq738CheVs",
    Reload:
      "https://drive.google.com/uc?export=view&id=1mMZfFkIK9izUpGmM5dqi_UM9vwUeMWFT",
    Ex: "https://drive.google.com/uc?export=view&id=1FnKV1pUXaDk9tc-kiVGasuISliXymrFs",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=15k6FKjBpv9gVgBJ-cXqoffKKiF_ZabRL",
    Pick: "https://drive.google.com/uc?export=view&id=1fcmII_rdP2kMEENg_2s0Z8Y-giaUBMlt",
    Hide: "https://drive.google.com/uc?export=view&id=1pjT0ZDVysij67xRIDgEnXZXBMMgCMq7D",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1gzzepuvoP4gd33efQ2AxDPYQC1mDBDeU",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1lfoxkklnHfCco_t-gWkZ0gDUMwLOxqCw",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Tsukuyo",
    Kname: "츠쿠요",
    Ns: "https://drive.google.com/uc?export=view&id=1vTQq25iLDrrCPhAF9bNt_NH6jqF_3yaV",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d3e234a0b108b32cf2ab" },
    Win: "https://drive.google.com/uc?export=view&id=12BxTvHlpzv_3rOPCAtf6M9hHxbvLAS2S",
    Start:
      "https://drive.google.com/uc?export=view&id=1dQU-KVSEpba6pr4UTC7wDheQMS5n4M-f",
    Reload:
      "https://drive.google.com/uc?export=view&id=1B0CUnXSy8NkS4XXJ0nsA29mQ8_2tSW9G",
    Ex: "https://drive.google.com/uc?export=view&id=1bWw4jH2A9rKdZzOfSiD4t7MDsGol9D00",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1fkDu6V-pdtE_dmzhyjrZixq-FBCeBfYY",
    Pick: "https://drive.google.com/uc?export=view&id=1S8c1uHhbkI-ostcIz52O2Uz85FryL18K",
    Hide: "https://drive.google.com/uc?export=view&id=19qN2RjyXSWmk4ZChWY74zxixa2jCOwqL",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1zLaf99i4QDD0rXgT4Olx60jv-KZlwjv3",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1SPHsUzFGAG7Dw3oa681Tll7ug6op5Z8X",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Atsuko",
    Kname: "아츠코",
    Ns: "https://drive.google.com/uc?export=view&id=1hEnuh9zpZoqhNRNrtjBMg3CPuCpvpmuH",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d45e34a0b108b32cf2ac" },
    Win: "https://drive.google.com/uc?export=view&id=15N_t3dVYK9kSJBRgxbLheOCaKM5BqDFQ",
    Start:
      "https://drive.google.com/uc?export=view&id=1vnm0g9MhyRevvEsqiTuTYfYK1l9k1Gf5",
    Reload:
      "https://drive.google.com/uc?export=view&id=1yPn4MkC5dYit-8BrCzbON9GTDKE0Wh9h",
    Ex: "https://drive.google.com/uc?export=view&id=1OlDO3kPoTXtrHsh-xJO1077GgDAiPvbj",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=14G6hLHPPAv2_aaWZ862r2flMP787dhYe",
    Pick: "https://drive.google.com/uc?export=view&id=1fCqVsV5g0ca8x7PTFk6A_RDXg-JsRzQ5",
    Hide: "https://drive.google.com/uc?export=view&id=15ICw98erinK8jhUvuzj_WO6_b5G6aSsU",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1TqwBN6aneOzsgIz5vvIIQWczys6aCQjP",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1xem-rgqYj5Gt2-Xtus1U-1WyCpqTv9e2",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1gGesmxNQaOJa7dE2h8IU89WdRy5YXttp",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1YCcf5o1HPfpwddHSQWs4PLLysdhbFL4T",
    ExReload: "",
    Name: "Wakamo-Swim",
    Kname: "와카모(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=17oULA9OJSf6I_EsJFeVnKb9j2zQhZvHH",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d62534a0b108b32cf2ad" },
    Win: "https://drive.google.com/uc?export=view&id=1aksJlLv2lWiB5dA_Inp2mFkKCXMUlAzW",
    Start:
      "https://drive.google.com/uc?export=view&id=1jfNTrTBxWZkbjQ7SccqxvSXaz5LKTAxC",
    Reload:
      "https://drive.google.com/uc?export=view&id=12HvgIjxFMs9_3UhLoCZYoVgwu6M8zqEI",
    Ex: "https://drive.google.com/uc?export=view&id=1I3DaXw_IDZNepqPOQShHN3n8IQ6nwLA5",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=12ygm3-cEpdPn30QuwZaKUHtxVzCfu1wU",
    Pick: "https://drive.google.com/uc?export=view&id=1AvF4lqIZmwC4u4MbVhLytIc6w3CE5yG4",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1al2RCj6J2F70EzYI-oBk_b7wKGlV4rCX",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=12EdSWxVeXsHhCyB0FHN-7yKExoqmvwik",
    ExReload: "",
    Name: "Nonomi-Swim",
    Kname: "노노미(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1bTdiHaEnKJ4vqHAFRM5QcmUdAe_WMwhj",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d6f534a0b108b32cf2ae" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1ue9zvVor7R6zi_cTJawgGG1ns3Hn4TUX",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1UvRV54ht0na4t2-jVTfYzIpGREZHkGON",
    ExAttack:
      "https://drive.google.com/uc?export=view&id=1mdJVYIEqZNkKA9-UCbJIyTs2KtY7MKHg",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload:
      "https://drive.google.com/uc?export=view&id=1EjztHLM3mhpzVDewbkxahNeK2w-92ic1",
    Name: "Ayane-Swim",
    Kname: "아야네(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1M0yKsGNDDIK8epu5Wx4VrBNTc_5sBApi",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d74d34a0b108b32cf2af" },
    Win: "https://drive.google.com/uc?export=view&id=1xuX_fv74r9Nme7UzSLkjdi8iAoQKoQ07",
    Start:
      "https://drive.google.com/uc?export=view&id=1aBeH7B6Sv0ieEYagRpMZZs06FTD3f-3O",
    Reload:
      "https://drive.google.com/uc?export=view&id=1M5v99NyN1onGnwT8ZCiaw3WMLasmt10F",
    Ex: "https://drive.google.com/uc?export=view&id=15XOb3Opw1FYHgIkQ80C0Oix5nrDMlB0t",
    ExAttack:
      "https://drive.google.com/uc?export=view&id=17aTtC-sk2tUBi6vhaWfnpI457WR20fjK",
    Attack:
      "https://drive.google.com/uc?export=view&id=1AmXW63BC-6o4onXLzc-YH5F8zD5xk6ME",
    Pick: "https://drive.google.com/uc?export=view&id=15OZaey5PVia5Jzt1jVjCMhkwNSdKjgnS",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1h0mOQWmxO5kEvEBATUjcP276-ctszzaz",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1R1GIk9Q2EB_Ag9iVy9jERmSKeSJoe9cT",
    ExReload: "",
    Name: "Hoshino-Swim",
    Kname: "호시노(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1n-S6UqplN8NKnZxTBszLQtIXspCnpzzi",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d7d834a0b108b32cf2b0" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1jorM54w9mMPk2YPfSKtbsaCwBvnOKmoE",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1sxkEFi24jObZwhPGATZcd-ie4KLMK1PS",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1gqzgwUlurqnSAHDAERqFZyFV-Y0Z3PPp",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1meOJf-8ZF0jVVqaxDnO6pDxV8HGRNjNC",
    ExReload: "",
    Name: "Shizuko-Swim",
    Kname: "시즈코(수영복)",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d81534a0b108b32cf2b1" },
    Win: "https://drive.google.com/uc?export=view&id=1HyRK6ugPajwDcD_hEh2ijaigPhGDIsDM",
    Start:
      "https://drive.google.com/uc?export=view&id=1z2r1MkmuXj9LsmvSWCj0wNf-H06r6ZWt",
    Reload:
      "https://drive.google.com/uc?export=view&id=1ZYdj3FynFFRrNZd__xRNGtjhPT0oD4gk",
    Ex: "https://drive.google.com/uc?export=view&id=19p--KYukg8ZWrxrE6iRH4uwap2aOruL3",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1jUEw7cG3SAsVJ1cIPdJ6nms-TYoPP6qu",
    Pick: "https://drive.google.com/uc?export=view&id=1SROg82Hg51e2lLHEo2AUQuXv1KCp8Ac6",
    Hide: "https://drive.google.com/uc?export=view&id=1lJ3oc5F6Wp2v7VUhAc3dyVMifMaM3JVj",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1gO5evJK2aJQVopLAkcNL9me2S7EoYVVn",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1hROiOB0gNTWxV5ym_JYlyXDhGH81nACu",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1Tq3X2fVoe7gnfPEgS5bOXIUcv62LBxaU",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1V0PKEfZgV5iwDXxZSFSjnNi27S2xRu8O",
    ExReload: "",
    Name: "Izuna-Swim",
    Kname: "이즈나(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1OCmBMl8EeRaurTl5b-AtBe_2bO3UsRiz",
    ExNs: "",
    HideReload2:
      "https://drive.google.com/uc?export=view&id=1jdTh7lH-Al1BtXpKLubUs3jzqehzVzbJ",
    Reload2:
      "https://drive.google.com/uc?export=view&id=1AA9byCZxycriB2RBbuXcVLjkay7IgOW9",
    Start2:
      "https://drive.google.com/uc?export=view&id=1yVm1WiQJBpcK-tvXIA2G8AbuGqspkCgo",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d8f534a0b108b32cf2b2" },
    Win: "https://drive.google.com/uc?export=view&id=16ayyIXxXZAWrRtE8JzFwJkTLdGjJ8ugl",
    Start:
      "https://drive.google.com/uc?export=view&id=1JREi01sS-xVhBncv1mIBO_UAKxYjhwEZ",
    Reload:
      "https://drive.google.com/uc?export=view&id=1AY2MN_hE2Opgg3OA7DP2xjSp6Vcvylsh",
    Ex: "https://drive.google.com/uc?export=view&id=140fY0hliGCov5R778ye3iPXm_cO_sy1o",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1V-sU8MuaN8p2GiReUvXp6P75GzJsidm-",
    Pick: "https://drive.google.com/uc?export=view&id=193J4Tsqe5CAXB4CEBwZas6anJ3mOuuN3",
    Hide: "https://drive.google.com/uc?export=view&id=1VCEde4F_vKJWP5Kg7Yz8c7QJdgMBH4hm",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1Q9BiutDrmJMmR3BWhgbW5ip9UJdHI1bV",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1EnVdypyDvef1qSCL9YthkPeV62P6a_5e",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Chise-Swim",
    Kname: "치세(수영복)",
    Ns: "https://drive.google.com/uc?export=view&id=1lYQ9libkhMOS5Nil55TLJkSXJdiXIOI9",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576d9db34a0b108b32cf2b3" },
    Win: "https://drive.google.com/uc?export=view&id=1W5Q-Set2VYKmXKhfAovLyAeNsKNMXLtT",
    Start:
      "https://drive.google.com/uc?export=view&id=1MO_r5zb38-UmYDByAbGccSem2H7eeJXB",
    Reload:
      "https://drive.google.com/uc?export=view&id=12mrXs_wuIlqnDx95ETeqTMsgnyknlvuH",
    Ex: "https://drive.google.com/uc?export=view&id=1aWiZPoBCb0NegZvja1qFzCVPbwF7QBdF",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=18xH2Ho1ug41E4toQhN8LT1Syo56rL6ml",
    Pick: "https://drive.google.com/uc?export=view&id=130CyM33lejZ9Dgq2_VxqQYUVU8igtXIj",
    Hide: "https://drive.google.com/uc?export=view&id=1gnkfUT-rqjzT8fMoagMWc4pa3rRNAb2W",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1h4Z6PZOMOrkuHU74NEhDFGBPYtb2flH_",
    HideReload:
      "https://drive.google.com/uc?export=view&id=121IM8bb2Y2iIsdsPdbm4BaJA_ceNRqQL",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1ggl1PMnirTqhCCh1nUruvo_QY5JNTcMn",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=13VeE6hnwNB8BWf7FPLUMD_egt0ql1VFW",
    ExReload: "",
    Name: "Saori",
    Kname: "사오리",
    Ns: "https://drive.google.com/uc?export=view&id=1juEu9PXRJ6v3_JvEUfTeLa8nUGc9n8is",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576fe1f4adc2c8711e5d5f3" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1XU1s2vECf2-exM2kw26YyasabyYcac88",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1bNoavhAFYCH2356NpGuc0BwU4fFXbzHf",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1rqz62EizlqwOVrUdl2D9RL_MPNGhIhiB",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1QN8K6fMoUcrpGKUM-exovQSiCN6AyFtv",
    ExReload: "",
    Name: "Moe",
    Kname: "모에",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576fe5c4adc2c8711e5d5f4" },
    Win: "https://drive.google.com/uc?export=view&id=1YZIdSr9_c2NUH5mKFDSG_ADft7pfSfUX",
    Start:
      "https://drive.google.com/uc?export=view&id=1Rfqhlcif25ulwD_1hRQr22rNBVLCqOCd",
    Reload:
      "https://drive.google.com/uc?export=view&id=1aTGnqUmDLqnvNFWzsfUXJFi247EeXJBZ",
    Ex: "https://drive.google.com/uc?export=view&id=1w5nQZ0hcNE6pUhdiayOXREvrXIvE_4Nm",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1gdsseQpghHB_G7-9sVUVCf3-rezM0RLW",
    Pick: "https://drive.google.com/uc?export=view&id=1rhsCkpdsNgNc5wEq44IPDXNnzpSp-98H",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1Ndd_K9RIWuzzO60G89HWsHGwUNIMhqaW",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1ZlOndWAuZIkegG5OgmRcTZs1tTLOoY8b",
    ExReload: "",
    Name: "Kazusa",
    Kname: "카즈사",
    Ns: "https://drive.google.com/uc?export=view&id=160oVzNdK_PDfY5XtakSxNXI3DUI75HyX",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
];
