export const localDB = [
  {
    Win: "/image/Aru/Aru_Win.webp",
    Start: "/image/Aru/Aru_Start.webp",
    Reload: "/image/Aru/Aru_Reload.webp",
    Ex: "/image/Aru/Aru_Ex.webp",
    ExAttack: "",
    Attack: "/image/Aru/Aru_Attack.webp",
    Pick: "/image/Aru/Aru_Pick.webp",
    Hide: "/image/Aru/Aru_Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Aru/Aru_Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Aru",
    Kname: "아루",
    Ns: "/image/Aru/Aru_1S.webp",
  },
  {
    Win: "/image/Aru_New/Aru_New-Win2.webp",
    Start: "/image/Aru_New/Aru_New-Start2.webp",
    Reload: "/image/Aru_New/Aru_New-Reload.webp",
    Ex: "/image/Aru_New/Aru_New-Ex.webp",
    ExAttack: "",
    Attack: "/image/Aru_New/Aru_New-Attack.webp",
    Pick: "/image/Aru_New/Aru_New-Pick.webp",
    Hide: "/image/Aru_New/Aru_New-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Aru_New/Aru_New-Cafe0.webm",
    Cafe2Webm: "/image/Aru_New/Aru_New-Cafe5.webm",
    ExReload: "",
    Name: "Aru_New",
    Kname: "아루(새해)",
    Ns: "/image/Aru_New/Aru_New-Ns.webp",
  },
  {
    Win: "/image/Eimi/Eimi-Win.webp",
    Start: "/image/Eimi/Eimi-Start.webp",
    Reload: "/image/Eimi/Eimi-Reload.webp",
    Ex: "/image/Eimi/Eimi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Eimi/Eimi-Attack.webp",
    Pick: "/image/Eimi/Eimi-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Eimi/Eimi-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Eimi",
    Kname: "에이미",
    Ns: "/image/Eimi/Eimi-1s.webp",
  },
  {
    Win: "/image/Haruna/Haruna-Win.webp",
    Start: "/image/Haruna/Haruna-Start.webp",
    Reload: "/image/Haruna/Haruna-Reload.webp",
    Ex: "/image/Haruna/Haruna-Ex.webp",
    ExAttack: "",
    Attack: "/image/Haruna/Haruna-Attack.webp",
    Pick: "/image/Haruna/Haruna-Pick.webp",
    Hide: "/image/Haruna/Haruna-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "/image/Haruna/Haruna-Cafe.webp",
    Cafe2: "",
    ExReload: "",
    Name: "Haruna",
    Kname: "하루나",
    Ns: "/image/Haruna/Haruna-1s.webp",
  },
  {
    Win: "/image/Hifumi/Hifumi-Win.webp",
    Start: "/image/Hifumi/Hifumi-Start.webp",
    Reload: "/image/Hifumi/Hifumi-Reload.webp",
    Ex: "/image/Hifumi/Hifumi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Hifumi/Hifumi-Attack.webp",
    Pick: "/image/Hifumi/Hifumi-Pick.webp",
    Hide: "/image/Hifumi/Hifumi-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "/image/Hifumi/Hifumi-Obj.webp",
    CafeWebm: "/image/Hifumi/Hifumi-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Hifumi",
    Kname: "히후미",
    Ns: "/image/Hifumi/Hifumi-1S.webp",
  },
  {
    Win: "/image/Hoshino/Hoshino-Win.webp",
    Start: "/image/Hoshino/Hoshino-Start.webp",
    Reload: "/image/Hoshino/Hoshino-Reload.webp",
    Ex: "/image/Hoshino/Hoshino-Ex.webp",
    ExAttack: "",
    Attack: "/image/Hoshino/Hoshino-Attack.webp",
    Pick: "/image/Hoshino/Hoshino-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "/image/Hoshino/Hoshino-Obj.webp",
    CafeWebm: "/image/Hoshino/Hoshino-Cafe0.webm",
    Cafe2Webm: "/image/Hoshino/Hoshino-Cafe5.webm",
    ExReload: "",
    Name: "Hoshino",
    Kname: "호시노",
    Ns: "/image/Hoshino/Hoshino-1S.webp",
  },
  {
    Win: "/image/Iori/Iori-Win.webp",
    Start: "/image/Iori/Iori-Start.webp",
    Reload: "/image/Iori/Iori-Reload.webp",
    Ex: "/image/Iori/Iori-Ex.webp",
    ExAttack: "",
    Attack: "/image/Iori/Iori-Attack.webp",
    Pick: "/image/Iori/Iori-Pick.webp",
    Hide: "/image/Iori/Iori-Hide.webp",
    HideAttack: "/image/Iori/Iori-HideAttack.webp",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Iori/Iori-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Iori",
    Kname: "이오리",
    Ns: "/image/Iori/Iori-1S.webp",
  },
  {
    Win: "/image/Maki/Maki-Win.webp",
    Start: "/image/Maki/Maki-Start.webp",
    Reload: "/image/Maki/Maki-Reload.webp",
    Ex: "/image/Maki/Maki-Ex.webp",
    ExAttack: "",
    Attack: "/image/Maki/Maki-Attack.webp",
    Pick: "/image/Maki/Maki-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Maki/Maki-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Maki",
    Kname: "마키",
    Ns: "/image/Maki/Maki-1S.webp",
  },
  {
    Win: "/image/Neru/Neru-Win.webp",
    Start: "/image/Neru/Neru-Start.webp",
    Reload: "/image/Neru/Neru-Reload.webp",
    Ex: "/image/Neru/Neru-Ex.webp",
    ExAttack: "",
    Attack: "/image/Neru/Neru-Attack.webp",
    Pick: "/image/Neru/Neru-Pick.webp",
    Hide: "/image/Neru/Neru-Hide.webp",
    HideAttack: "/image/Neru/Neru-HideAttack.webp",
    HideReload: "/image/Neru/Neru-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Neru/Neru-Cafe0.webm",
    Cafe2Webm: "/image/Neru/Neru-Cafe5.webm",
    ExReload: "",
    Name: "Neru",
    Kname: "네루",
    Ns: "/image/Neru/Neru-1S.webp",
  },
  {
    Win: "/image/Izumi/Izumi-Win.webp",
    Start: "/image/Izumi/Izumi-Start.webp",
    Reload: "/image/Izumi/Izumi-Reload.webp",
    Ex: "/image/Izumi/Izumi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Izumi/Izumi-Attack.webp",
    Pick: "/image/Izumi/Izumi-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Izumi/Izumi-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Izumi",
    Kname: "이즈미",
    Ns: "/image/Izumi/Izumi-1S.webp",
  },
  {
    Win: "/image/Shiroko/Shiroko-Win.webp",
    Start: "/image/Shiroko/Shiroko-Start.webp",
    Reload: "/image/Shiroko/Shiroko-Reload.webp",
    Ex: "/image/Shiroko/Shiroko-Ex.webp",
    ExAttack: "",
    Attack: "/image/Shiroko/Shiroko-Attack.webp",
    Pick: "/image/Shiroko/Shiroko-Pick.webp",
    Hide: "/image/Shiroko/Shiroko-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Shiroko/Shiroko-Cafe0.webm",
    Cafe2Webm: "/image/Shiroko/Shiroko-Cafe5.webm",
    ExReload: "",
    Name: "Shiroko",
    Kname: "시로코",
    Ns: "/image/Shiroko/Shiroko-1S.webp",
  },
  {
    Win: "/image/Shun/Shun-Win.webp",
    Start: "/image/Shun/Shun-Start.webp",
    Reload: "/image/Shun/Shun-Reload.webp",
    Ex: "/image/Shun/Shun-Ex.webp",
    ExAttack: "/image/Shun/Shun-ExAttack.webp",
    Attack: "/image/Shun/Shun-Attack.webp",
    Pick: "/image/Shun/Shun-Pick.webp",
    Hide: "/image/Shun/Shun-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Shun/Shun-Cafe0.webm",
    Cafe2: "",
    ExReload: "/image/Shun/Shun-ExReload.webp",
    Name: "Shun",
    Kname: "슌",
    Ns: "/image/Shun/Shun-1S.webp",
  },
  {
    Win: "/image/Sumire/Sumire-Win.webp",
    Start: "/image/Sumire/Sumire-Start.webp",
    Reload: "/image/Sumire/Sumire-Reload.webp",
    Ex: "/image/Sumire/Sumire-Ex.webp",
    ExAttack: "",
    Attack: "/image/Sumire/Sumire-Attack.webp",
    Pick: "/image/Sumire/Sumire-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "/image/Sumire/Sumire-Cafe.webp",
    Cafe2: "",
    ExReload: "",
    Name: "Sumire",
    Kname: "스미레",
    Ns: "/image/Sumire/Sumire-1S.webp",
  },
  {
    _id: { $oid: "656c5da3ab8d21c1d5b9b4c4" },
    Win: "/image/Tsurugi/Tsurugi-Win.webp",
    Start: "/image/Tsurugi/Tsurugi-Start.webp",
    Reload: "/image/Tsurugi/Tsurugi-Reload.webp",
    Ex: "/image/Tsurugi/Tsurugi-Ex.webp",
    ExAttack: "/image/Tsurugi/Tsurugi-ExAttack.webp",
    Attack: "/image/Tsurugi/Tsurugi-Attack.webp",
    Pick: "/image/Tsurugi/Tsurugi-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Tsurugi/Tsurugi-Cafe0.webm",
    Cafe2: "",
    ExReload: "/image/Tsurugi/Tsurugi-ExReload.webp",
    Name: "Tsurugi",
    Kname: "츠루기",
    Ns: "/image/Tsurugi/Tsurugi-Ns.webp",
  },
  {
    Win: "/image/Akane/Akane-Win.webp",
    Start: "/image/Akane/Akane-Start.webp",
    Reload: "/image/Akane/Akane-Reload.webp",
    Ex: "/image/Akane/Akane-Ex.webp",
    ExAttack: "",
    Attack: "/image/Akane/Akane-Attack.webp",
    Pick: "/image/Akane/Akane-Pick.webp",
    Hide: "/image/Akane/Akane-Hide.webp",
    HideAttack: "",
    HideReload: "/image/Akane/Akane-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Akane/Akane-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Akane",
    Kname: "아카네",
    Ns: "/image/Akane/Akane-Ns.webp",
  },
  {
    Win: "/image/Chise/Chise-Win.webp",
    Start: "/image/Chise/Chise-Start.webp",
    Reload: "/image/Chise/Chise-Reload.webp",
    Ex: "/image/Chise/Chise-Ex.webp",
    ExAttack: "",
    Attack: "/image/Chise/Chise-Attack.webp",
    Pick: "/image/Chise/Chise-Pick.webp",
    Hide: "/image/Chise/Chise-Hide.webp",
    HideAttack: "/image/Chise/Chise-HideAttack.webp",
    HideReload: "/image/Chise/Chise-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Chise/Chise-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Chise",
    Kname: "치세",
    Ns: "/image/Chise/Chise-Ns.webp",
  },
  {
    Win: "/image/Akari/Akari-Win.webp",
    Start: "/image/Akari/Akari-Start.webp",
    Reload: "/image/Akari/Akari-Reload.webp",
    Ex: "/image/Akari/Akari-Ex.webp",
    ExAttack: "",
    Attack: "/image/Akari/Akari-Attack.webp",
    Pick: "/image/Akari/Akari-Pick.webp",
    Hide: "/image/Akari/Akari-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Akari/Akari-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Akari",
    Kname: "아카리",
    Ns: "/image/Akari/Akari-Ns.webp",
  },
  {
    Win: "/image/Hasumi/Hasumi-Win.webp",
    Start: "/image/Hasumi/Hasumi-Start.webp",
    Reload: "/image/Hasumi/Hasumi-Reload.webp",
    Ex: "/image/Hasumi/Hasumi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Hasumi/Hasumi-Attack.webp",
    Pick: "/image/Hasumi/Hasumi-Pick.webp",
    Hide: "/image/Hasumi/Hasumi-Hide.webp",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Hasumi/Hasumi-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Hasumi",
    Kname: "하스미",
    Ns: "/image/Hasumi/Hasumi-Ns.webp",
  },
  {
    Win: "/image/Nonomi/Nonomi-Win.webp",
    Start: "/image/Nonomi/Nonomi-Start.webp",
    Reload: "/image/Nonomi/Nonomi-Reload.webp",
    Ex: "/image/Nonomi/Nonomi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Nonomi/Nonomi-Attack.webp",
    Pick: "/image/Nonomi/Nonomi-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Nonomi/Nonomi-Cafe0.webm",
    Cafe2Webm: "/image/Nonomi/Nonomi-Cafe5.webm",
    ExReload: "",
    Name: "Nonomi",
    Kname: "노노미",
    Ns: "/image/Nonomi/Nonomi-Ns.webp",
  },
  /* 1-20페이지 (1개는 스키마) */
  {
    Win: "/image/Kayoko/Kayoko-Win.webp",
    Start: "/image/Kayoko/Kayoko-Start.webp",
    Reload: "/image/Kayoko/Kayoko-Reload.webp",
    Ex: "/image/Kayoko/Kayoko-Ex.webp",
    ExAttack: "",
    Attack: "/image/Kayoko/Kayoko-Attack.webp",
    Pick: "/image/Kayoko/Kayoko-Pick.webp",
    Hide: "/image/Kayoko/Kayoko-Hide.webp",
    HideAttack: "/image/Kayoko/Kayoko-HideAttack.webp",
    HideReload: "/image/Kayoko/Kayoko-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Kayoko/Kayoko-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Kayoko",
    Kname: "카요코",
    Ns: "/image/Kayoko/Kayoko-Ns.webp",
  },
  {
    Win: "/image/Mutsuki/Mutsuki-Win.webp",
    Start: "/image/Mutsuki/Mutsuki-Start.webp",
    Reload: "/image/Mutsuki/Mutsuki-Reload.webp",
    Ex: "/image/Mutsuki/Mutsuki-Ex.webp",
    ExAttack: "",
    Attack: "/image/Mutsuki/Mutsuki-Attack.webp",
    Pick: "/image/Mutsuki/Mutsuki-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Mutsuki/Mutsuki-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Mutsuki",
    Kname: "무츠키",
    Ns: "/image/Mutsuki/Mutsuki-Ns.webp",
  },
  {
    Win: "/image/Junko/Junko-Win.webp",
    Start: "/image/Junko/Junko-Start.webp",
    Reload: "/image/Junko/Junko-Reload.webp",
    Ex: "/image/Junko/Junko-Ex.webp",
    ExAttack: "",
    Attack: "/image/Junko/Junko-Attack.webp",
    Pick: "/image/Junko/Junko-Pick.webp",
    Hide: "/image/Junko/Junko-Hide.webp",
    HideAttack: "",
    HideReload: "/image/Junko/Junko-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Junko/Junko-Cafe0.webm",
    Cafe2Webm: "/image/Junko/Junko-Cafe5.webm",
    ExReload: "",
    Name: "Junko",
    Kname: "준코",
    Ns: "/image/Junko/Junko-Ns.webp",
  },
  {
    Win: "/image/Serika/Serika-Win.webp",
    Start: "/image/Serika/Serika-Start.webp",
    Reload: "/image/Serika/Serika-Reload.webp",
    Ex: "/image/Serika/Serika-Ex.webp",
    ExAttack: "",
    Attack: "/image/Serika/Serika-Attack.webp",
    Pick: "/image/Serika/Serika-Pick.webp",
    Hide: "/image/Serika/Serika-Hide.webp",
    HideAttack: "",
    HideReload: "/image/Serika/Serika-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Serika/Serika-Cafe0.webm",
    Cafe2Webm: "/image/Serika/Serika-Cafe5.webm",
    ExReload: "",
    Name: "Serika",
    Kname: "세리카",
    Ns: "/image/Serika/Serika-Ns.webp",
  },
  {
    Win: "/image/Tsubaki/Tsubaki-Win.webp",
    Start: "/image/Tsubaki/Tsubaki-Start.webp",
    Reload: "/image/Tsubaki/Tsubaki-Reload.webp",
    Ex: "/image/Tsubaki/Tsubaki-Ex.webp",
    ExAttack: "",
    Attack: "/image/Tsubaki/Tsubaki-Attack.webp",
    Pick: "/image/Tsubaki/Tsubaki-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Tsubaki/Tsubaki-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Tsubaki",
    Kname: "츠바키",
    Ns: "/image/Tsubaki/Tsubaki-Ns.webp",
  },
  {
    Win: "/image/Yuuka/Yuuka-Win.webp",
    Start: "/image/Yuuka/Yuuka-Start.webp",
    Reload: "/image/Yuuka/Yuuka-Reload.webp",
    Ex: "/image/Yuuka/Yuuka-Ex.webp",
    ExAttack: "",
    Attack: "/image/Yuuka/Yuuka-Attack.webp",
    Pick: "/image/Yuuka/Yuuka-Pick.webp",
    Hide: "/image/Yuuka/Yuuka-Hide.webp",
    HideAttack: "/image/Yuuka/Yuuka-HideAttack.webp",
    HideReload: "/image/Yuuka/Yuuka-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Yuuka/Yuuka-Cafe.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Yuuka",
    Kname: "유우카",
    Ns: "/image/Yuuka/Yuuka-Ns.webp",
  },
  {
    Win: "/image/Haruka/Haruka-Win.webp",
    Start: "/image/Haruka/Haruka-Start.webp",
    Reload: "/image/Haruka/Haruka-Reload.webp",
    Ex: "/image/Haruka/Haruka-Ex.webp",
    ExAttack: "",
    Attack: "/image/Haruka/Haruka-Attack.webp",
    Pick: "/image/Haruka/Haruka-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Haruka/Haruka-Cafe0.webm",
    Cafe2Webm: "/image/Haruka/Haruka-Cafe5.webm",
    ExReload: "",
    Name: "Haruka",
    Kname: "하루카",
    Ns: "/image/Haruka/Haruka-Ns.webp",
  },
  {
    Win: "/image/Asuna/Asuna-Win.webp",
    Start: "/image/Asuna/Asuna-Start.webp",
    Reload: "/image/Asuna/Asuna-Reload.webp",
    Ex: "/image/Asuna/Asuna-Ex.webp",
    ExAttack: "",
    Attack: "/image/Asuna/Asuna-Attack.webp",
    Pick: "/image/Asuna/Asuna-Pick.webp",
    Hide: "/image/Asuna/Asuna-Hide.webp",
    HideAttack: "",
    HideReload: "/image/Asuna/Asuna-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Asuna/Asuna-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Asuna",
    Kname: "아스나",
    Ns: "/image/Asuna/Asuna-Ns.webp",
  },
  {
    Win: "/image/Kotori/Kotori-Win.webp",
    Start: "/image/Kotori/Kotori-Start.webp",
    Reload: "/image/Kotori/Kotori-Reload.webp",
    Ex: "/image/Kotori/Kotori-Ex.webp",
    ExAttack: "",
    Attack: "/image/Kotori/Kotori-Attack.webp",
    Pick: "/image/Kotori/Kotori-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Kotori/Kotori-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Kotori",
    Kname: "코토리",
    Ns: "/image/Kotori/Kotori-Ns.webp",
  },
  {
    Win: "/image/Suzumi/Suzumi-Win.webp",
    Start: "/image/Suzumi/Suzumi-Start.webp",
    Reload: "/image/Suzumi/Suzumi-Reload.webp",
    Ex: "/image/Suzumi/Suzumi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Suzumi/Suzumi-Attack.webp",
    Pick: "/image/Suzumi/Suzumi-Pick.webp",
    Hide: "/image/Suzumi/Suzumi-Hide.webp",
    HideAttack: "",
    HideReload: "/image/Suzumi/Suzumi-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Suzumi/Suzumi-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Suzumi",
    Kname: "스즈미",
    Ns: "/image/Suzumi/Suzumi-Ns.webp",
  },
  {
    Win: "/image/Pina/Pina-Win.webp",
    Start: "/image/Pina/Pina-Start.webp",
    Reload: "/image/Pina/Pina-Reload.webp",
    Ex: "/image/Pina/Pina-Ex.webp",
    ExAttack: "",
    Attack: "/image/Pina/Pina-Attack.webp",
    Pick: "/image/Pina/Pina-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Pina/Pina-Cafe0.webm",
    Cafe2Webm: "/image/Pina/Pina-Cafe5.webm",
    ExReload: "",
    Name: "Pina",
    Kname: "피나",
    Ns: "/image/Pina/Pina-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Hibiki/Hibiki-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Hibiki/Hibiki-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Hibiki",
    Kname: "히비키",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Karin/Karin-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Karin/Karin-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Karin",
    Kname: "카린",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Saya/Saya-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Saya/Saya-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Saya",
    Kname: "사야",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Airi/Airi-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Airi/Airi-Cafe0.webm",
    Cafe2Webm: "/image/Airi/Airi-Cafe5.webm",
    ExReload: "",
    Name: "Airi",
    Kname: "아이리",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Fuuka/Fuuka-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Fuuka/Fuuka-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Fuuka",
    Kname: "후우카",
    Ns: "",
  },

  {
    Win: "",
    Start: "/image/Hanae/Hanae-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Hanae/Hanae-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Hanae",
    Kname: "하나에",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Hare/Hare-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "/image/Hare/Hare-Cafe.webp",
    Cafe2: "",
    ExReload: "",
    Name: "Hare",
    Kname: "하레",
    Ns: "",
  },
  {
    _id: { $oid: "656fd6ad6a3dd9a4271f5e1c" },
    Win: "",
    Start: "/image/Utaha/Utaha-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Utaha/Utaha-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Utaha",
    Kname: "우타하",
    Ns: "",
  },
  {
    _id: { $oid: "656fd7c76a3dd9a4271f5e1d" },
    Win: "",
    Start: "/image/Ayane/Ayane-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Ayane/Ayane-Cafe0.webm",
    Cafe2Webm: "/image/Ayane/Ayane-Cafe5.webm",
    ExReload: "",
    Name: "Ayane",
    Kname: "아야네",
    Ns: "",
  },
  /* --- 21-40 까지  */
  {
    Win: "",
    Start: "/image/Chinatsu/Chinatsu-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Chinatsu/Chinatsu-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Chinatsu",
    Kname: "치나츠",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Kotama/Kotama-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Kotama/Kotama-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Kotama",
    Kname: "코타마",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Juri/Juri-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Juri/Juri-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Juri",
    Kname: "주리",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Serina/Serina-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Serina/Serina-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Serina",
    Kname: "세리나",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Shimiko/Shimiko-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "/image/Shimiko/Shimiko-Cafe.webp",
    Cafe2: "",
    ExReload: "",
    Name: "Shimiko",
    Kname: "시미코",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Yoshimi/Yoshimi-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Yoshimi/Yoshimi-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Yoshimi",
    Kname: "요시미",
    Ns: "",
  },
  {
    Win: "/image/Izuna/Izuna-Win.webp",
    Start: "/image/Izuna/Izuna-Start.webp",
    Reload: "/image/Izuna/Izuna-Reload.webp",
    Ex: "/image/Izuna/Izuna-Ex.webp",
    ExAttack: "",
    Attack: "/image/Izuna/Izuna-Attack.webp",
    Pick: "/image/Izuna/Izuna-Pick.webp",
    Hide: "/image/Izuna/Izuna-Hide.webp",
    HideAttack: "/image/Izuna/Izuna-HideAttack.webp",
    HideReload: "/image/Izuna/Izuna-HideReload.webp",
    Object: "/image/Izuna/Izuna-Obj.webp",
    CafeWebm: "/image/Izuna/Izuna-Cafe0.webm",
    Cafe2Webm: "/image/Izuna/Izuna-Cafe5.webm",
    ExReload: "",
    Name: "Izuna",
    Kname: "이즈나",
    Ns: "/image/Izuna/Izuna-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Shizuko/Shizuko-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Shizuko/Shizuko-Cafe0.webm",
    Cafe2Webm: "/image/Shizuko/Shizuko-Cafe5.webm",
    ExReload: "",
    Name: "Shizuko",
    Kname: "시즈코",
    Ns: "",
  },
  {
    Win: "/image/Aris/Aris-Win.webp",
    Start: "/image/Aris/Aris-Start.webp",
    Reload: "/image/Aris/Aris-Reload.webp",
    Ex: "/image/Aris/Aris-Ex.webp",
    ExAttack: "",
    Attack: "/image/Aris/Aris-Attack.webp",
    Pick: "/image/Aris/Aris-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Aris/Aris-Cafe0.webm",
    Cafe2Webm: "/image/Aris/Aris-Cafe5.webm",
    Cafe3Webm: "/image/Aris/Aris-Cafe6.webm",
    ExReload: "",
    Name: "Aris",
    Kname: "아리스",
    Ns: "/image/Aris/Aris-Ns.webp",
  },
  {
    Win: "/image/Midori/Midori-Win.webp",
    Start: "/image/Midori/Midori-Start.webp",
    Reload: "/image/Midori/Midori-Reload.webp",
    Ex: "/image/Midori/Midori-Ex.webp",
    ExAttack: "",
    Attack: "/image/Midori/Midori-Attack.webp",
    Pick: "/image/Midori/Midori-Pick.webp",
    Hide: "/image/Midori/Midori-Hide.webp",
    HideAttack: "/image/Midori/Midori-HideAttack.webp",
    HideReload: "/image/Midori/Midori-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Midori/Midori-Cafe0.webm",
    Cafe2Webm: "/image/Midori/Midori-Cafe5.webm",
    Cafe3Webm: "/image/Midori/Midori-Cafe6.webm",
    ExReload: "",
    Name: "Midori",
    Kname: "미도리",
    Ns: "/image/Midori/Midori-Ns.webp",
  },
  {
    Win: "/image/Momoi/Momoi-Win.webp",
    Start: "/image/Momoi/Momoi-Start.webp",
    Reload: "/image/Momoi/Momoi-Reload.webp",
    Ex: "/image/Momoi/Momoi-Ex.webp",
    ExAttack: "",
    Attack: "/image/Momoi/Momoi-Attack.webp",
    Pick: "/image/Momoi/Momoi-Pick.webp",
    Hide: "/image/Momoi/Momoi-Hide.webp",
    HideAttack: "/image/Momoi/Momoi-HideAttack.webp",
    HideReload: "/image/Momoi/Momoi-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Momoi/Momoi-Cafe0.webm",
    Cafe2Webm: "/image/Momoi/Momoi-Cafe5.webm",
    ExReload: "",
    Name: "Momoi",
    Kname: "모모이",
    Ns: "/image/Momoi/Momoi-Ns.webp",
  },
  {
    Win: "/image/Cherino/Cherino-Win.webp",
    Start: "/image/Cherino/Cherino-Start.webp",
    Reload: "/image/Cherino/Cherino-Reload.webp",
    Ex: "/image/Cherino/Cherino-Ex.webp",
    ExAttack: "",
    Attack: "/image/Cherino/Cherino-Attack.webp",
    Pick: "/image/Cherino/Cherino-Pick.webp",
    Hide: "/image/Cherino/Cherino-Hide.webp",
    HideAttack: "/image/Cherino/Cherino-HideAttack.webp",
    HideReload: "/image/Cherino/Cherino-HideReload.webp",
    Object: "",
    Cafe: "/image/Cherino/Cherino-Cafe.webp",
    Cafe2: "",
    ExReload: "",
    Name: "Cherino",
    Kname: "체리노",
    Ns: "/image/Cherino/Cherino-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Nodoka/Nodoka-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Nodoka/Nodoka-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Nodoka",
    Kname: "노도카",
    Ns: "",
  },
  {
    Win: "/image/Azusa/Azusa-Win.webp",
    Start: "/image/Azusa/Azusa-Start.webp",
    Reload: "/image/Azusa/Azusa-Reload.webp",
    Ex: "/image/Azusa/Azusa-Ex.webp",
    ExAttack: "",
    Attack: "/image/Azusa/Azusa-Attack.webp",
    Pick: "/image/Azusa/Azusa-Pick.webp",
    Hide: "/image/Azusa/Azusa-Hide.webp",
    HideAttack: "/image/Azusa/Azusa-HideAttack.webp",
    HideReload: "/image/Azusa/Azusa-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Azusa/Azusa-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Azusa",
    Kname: "아즈사",
    Ns: "/image/Azusa/Azusa-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Hanako/Hanako-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Hanako/Hanako-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Hanako",
    Kname: "하나코",
    Ns: "",
  },
  {
    Win: "/image/Azusa_Swim/Azusa_Swim-Win.webp",
    Start: "/image/Azusa_Swim/Azusa_Swim-Start.webp",
    Reload: "/image/Azusa_Swim/Azusa_Swim-Reload.webp",
    Ex: "/image/Azusa_Swim/Azusa_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Azusa_Swim/Azusa_Swim-Attack.webp",
    Pick: "/image/Azusa_Swim/Azusa_Swim-Pick.webp",
    Hide: "/image/Azusa_Swim/Azusa_Swim-Hide.webp",
    HideAttack: "/image/Azusa_Swim/Azusa_Swim-HideAttack.webp",
    HideReload: "/image/Azusa_Swim/Azusa_Swim-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Azusa_Swim/Azusa_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Azusa_Swim/Azusa_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Azusa-Swim",
    Kname: "아즈사(수영복)",
    Ns: "/image/Azusa_Swim/Azusa_Swim-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Mashiro_Swim/Mashiro_Swim-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Mashiro_Swim/Mashiro_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Mashiro_Swim/Mashiro_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Mashiro-Swim",
    Kname: "마시로(수영복)",
    Ns: "",
  },
  {
    Win: "/image/Tsurugi_Swim/Tsurugi_Swim-Win.webp",
    Start: "/image/Tsurugi_Swim/Tsurugi_Swim-Start.webp",
    Reload: "/image/Tsurugi_Swim/Tsurugi_Swim-Reload.webp",
    Ex: "/image/Tsurugi_Swim/Tsurugi_Swim-Ex.webp",
    ExAttack: "/image/Tsurugi_Swim/Tsurugi_Swim-ExAttack.webp",
    Attack: "/image/Tsurugi_Swim/Tsurugi_Swim-Attack.webp",
    Pick: "/image/Tsurugi_Swim/Tsurugi_Swim-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Tsurugi_Swim/Tsurugi_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Tsurugi_Swim/Tsurugi_Swim-Cafe5.webm",
    ExReload: "/image/Tsurugi_Swim/Tsurugi_Swim-ExReload.webp",
    Name: "Tsurugi-Swim",
    Kname: "츠루기(수영복)",
    Ns: "/image/Tsurugi_Swim/Tsurugi_Swim-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Hifumi_Swim/Hifumi_Swim-Start.webp",
    Reload: "",
    Ex: "/image/Hifumi_Swim/Hifumi_Swim-Ex.webp",
    ExAttack: "/image/Hifumi_Swim/Hifumi_Swim-ExAttack.webp",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Hifumi_Swim/Hifumi_Swim-Cafe0.webm",
    Cafe2: "",
    ExReload: "/image/Hifumi_Swim/Hifumi_Swim-ExReload.webp",
    Name: "Hifumi-Swim",
    Kname: "히후미(수영복)",
    Ns: "",
    ExNs: "/image/Hifumi_Swim/Hifumi_Swim-ExNs.webp",
  },
  {
    Win: "/image/Izumi_Swim/Izumi_Swim-Win.webp",
    Start: "/image/Izumi_Swim/Izumi_Swim-Start.webp",
    Reload: "/image/Izumi_Swim/Izumi_Swim-Reload.webp",
    Reload2: "/image/Izumi_Swim/Izumi_Swim-Reload2.webp",
    Ex: "/image/Izumi_Swim/Izumi_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Izumi_Swim/Izumi_Swim-Attack.webp",
    Pick: "/image/Izumi_Swim/Izumi_Swim-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Izumi_Swim/Izumi_Swim-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Izumi-Swim",
    Kname: "이즈미(수영복)",
    Ns: "/image/Izumi_Swim/Izumi_Swim-Ns.webp",
  },
  /* 41-60 까지 */
  {
    Win: "/image/Shun_Small/Shun_Small-Win.webp",
    Start: "/image/Shun_Small/Shun_Small-Start.webp",
    Reload: "/image/Shun_Small/Shun_Small-Reload.webp",
    Ex: "/image/Shun_Small/Shun_Small-Ex.webp",
    ExAttack: "",
    Attack: "/image/Shun_Small/Shun_Small-Attack.webp",
    Pick: "/image/Shun_Small/Shun_Small-Pick.webp",
    Hide: "/image/Shun_Small/Shun_Small-Hide.webp",
    HideAttack: "/image/Shun_Small/Shun_Small-HideAttack.webp",
    HideReload: "/image/Shun_Small/Shun_Small-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Shun_Small/Shun_Small-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Shun-Small",
    Kname: "슌(어린이)",
    Ns: "/image/Shun_Small/Shun_Small-Ns.webp",
  },
  {
    Win: "/image/Kirino/Kirino-Win.webp",
    Start: "/image/Kirino/Kirino-Start.webp",
    Reload: "/image/Kirino/Kirino-Reload.webp",
    Ex: "/image/Kirino/Kirino-Ex.webp",
    ExAttack: "",
    Attack: "/image/Kirino/Kirino-Attack.webp",
    Pick: "/image/Kirino/Kirino-Pick.webp",
    Hide: "/image/Kirino/Kirino-Hide.webp",
    HideAttack: "/image/Kirino/Kirino-HideAttack.webp",
    HideReload: "/image/Kirino/Kirino-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Kirino/Kirino-Cafe0.webm",
    Cafe2: "",
    ExReload: "",
    Name: "Kirino",
    Kname: "키리노",
    Ns: "/image/Kirino/Kirino-Ns.webp",
  },
  {
    Win: "/image/Neru_Bunny/Neru_Bunny-Win.webp",
    Start: "/image/Neru_Bunny/Neru_Bunny-Start.webp",
    Reload: "/image/Neru_Bunny/Neru_Bunny-Reload.webp",
    Ex: "/image/Neru_Bunny/Neru_Bunny-Ex.webp",
    ExAttack: "",
    Attack: "/image/Neru_Bunny/Neru_Bunny-Attack.webp",
    Pick: "/image/Neru_Bunny/Neru_Bunny-Pick.webp",
    Hide: "/image/Neru_Bunny/Neru_Bunny-Hide.webp",
    HideAttack: "/image/Neru_Bunny/Neru_Bunny-HideAttack.webp",
    HideReload: "/image/Neru_Bunny/Neru_Bunny-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Neru_Bunny/Neru_Bunny-Cafe0.webm",
    Cafe2Webm: "/image/Neru_Bunny/Neru_Bunny-Cafe5.webm",
    ExReload: "",
    Name: "Neru-Bunny",
    Kname: "네루(바니걸)",
    Ns: "/image/Neru_Bunny/Neru_Bunny-Ns.webp",
  },
  {
    Win: "/image/Karin_Bunny/Karin_Bunny-Win.webp",
    Start: "/image/Karin_Bunny/Karin_Bunny-Start.webp",
    Reload: "/image/Karin_Bunny/Karin_Bunny-Reload.webp",
    Ex: "/image/Karin_Bunny/Karin_Bunny-Ex.webp",
    ExAttack: "",
    Attack: "/image/Karin_Bunny/Karin_Bunny-Attack.webp",
    Pick: "/image/Karin_Bunny/Karin_Bunny-Pick.webp",
    Hide: "/image/Karin_Bunny/Karin_Bunny-Hide.webp",
    HideAttack: "/image/Karin_Bunny/Karin_Bunny-HideAttack.webp",
    HideReload: "/image/Karin_Bunny/Karin_Bunny-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Karin_Bunny/Karin_Bunny-Cafe0.webm",
    Cafe2Webm: "/image/Karin_Bunny/Karin_Bunny-Cafe5.webm",
    ExReload: "",
    Name: "Karin-Bunny",
    Kname: "카린(바니걸)",
    Ns: "/image/Karin_Bunny/Karin_Bunny-Ns.webp",
  },
  {
    Win: "/image/Asuna_Bunny/Asuna_Bunny-Win.webp",
    Start: "/image/Asuna_Bunny/Asuna_Bunny-Start.webp",
    Reload: "/image/Asuna_Bunny/Asuna_Bunny-Reload.webp",
    Ex: "/image/Asuna_Bunny/Asuna_Bunny-Ex.webp",
    ExAttack: "",
    Attack: "/image/Asuna_Bunny/Asuna_Bunny-Attack.webp",
    Pick: "/image/Asuna_Bunny/Asuna_Bunny-Pick.webp",
    Hide: "/image/Asuna_Bunny/Asuna_Bunny-Hide.webp",
    HideAttack: "/image/Asuna_Bunny/Asuna_Bunny-HideAttack.webp",
    HideReload: "/image/Asuna_Bunny/Asuna_Bunny-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Asuna_Bunny/Asuna_Bunny-Cafe0.webm",
    Cafe2Webm: "/image/Asuna_Bunny/Asuna_Bunny-Cafe5.webm",
    ExReload: "",
    Name: "Asuna-Bunny",
    Kname: "아스나(바니걸)",
    Ns: "/image/Asuna_Bunny/Asuna_Bunny-Ns.webp",
  },
  {
    Win: "/image/Natsu/Natsu-Win.webp",
    Start: "/image/Natsu/Natsu-Start.webp",
    Reload: "/image/Natsu/Natsu-Reload.webp",
    Ex: "/image/Natsu/Natsu-Ex.webp",
    ExAttack: "",
    Attack: "/image/Natsu/Natsu-Attack.webp",
    Pick: "/image/Natsu/Natsu-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Natsu/Natsu-Cafe0.webm",
    Cafe2Webm: "/image/Natsu/Natsu-Cafe5.webm",
    ExReload: "",
    Name: "Natsu",
    Kname: "나츠",
    Ns: "/image/Natsu/Natsu-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Mari/Mari-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Mari/Mari-Cafe0.webm",
    Cafe2Webm: "/image/Mari/Mari-Cafe5.webm",
    ExReload: "",
    Name: "Mari",
    Kname: "마리",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Ako/Ako-Start.webp",
    Reload: "",
    Ex: "/image/Ako/Ako-Ex.webp",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Ako/Ako-Cafe0.webm",
    Cafe2Webm: "/image/Ako/Ako-Cafe5.webm",
    ExReload: "",
    Name: "Ako",
    Kname: "아코",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Cherino_Hot/Cherino_Hot-Start.webp",
    Reload: "",
    Ex: "/image/Cherino_Hot/Cherino_Hot-Ex.webp",
    ExAttack: "/image/Cherino_Hot/Cherino_Hot-ExAttack.webp",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Cherino_Hot/Cherino_Hot-Cafe0.webm",
    Cafe2Webm: "/image/Cherino_Hot/Cherino_Hot-Cafe5.webm",
    ExReload: "/image/Cherino_Hot/Cherino_Hot-ExReload.webp",
    Name: "Cherino-Hot",
    Kname: "체리노(온천)",
    Ns: "",
    ExNs: "/image/Cherino_Hot/Cherino_Hot-ExNs.webp",
  },
  {
    Win: "/image/Chinatsu_Hot/Chinatsu_Hot-Win.webp",
    Start: "/image/Chinatsu_Hot/Chinatsu_Hot-Start.webp",
    Reload: "/image/Chinatsu_Hot/Chinatsu_Hot-Reload.webp",
    Ex: "/image/Chinatsu_Hot/Chinatsu_Hot-Ex.webp",
    ExAttack: "",
    Attack: "/image/Chinatsu_Hot/Chinatsu_Hot-Attack.webp",
    Pick: "/image/Chinatsu_Hot/Chinatsu_Hot-Pick.webp",
    Hide: "/image/Chinatsu_Hot/Chinatsu_Hot-Hide.webp",
    HideAttack: "/image/Chinatsu_Hot/Chinatsu_Hot-HideAttack.webp",
    HideReload: "/image/Chinatsu_Hot/Chinatsu_Hot-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Chinatsu_Hot/Chinatsu_Hot-Cafe0.webm",
    Cafe2Webm: "/image/Chinatsu_Hot/Chinatsu_Hot-Cafe5.webm",
    ExReload: "",
    Name: "Chinatsu-Hot",
    Kname: "치나츠(온천)",
    Ns: "/image/Chinatsu_Hot/Chinatsu_Hot-Ns.webp",
  },
  {
    Win: "/image/Tomoe/Tomoe-Win.webp",
    Start: "/image/Tomoe/Tomoe-Start.webp",
    Reload: "/image/Tomoe/Tomoe-Reload.webp",
    Ex: "/image/Tomoe/Tomoe-Ex.webp",
    ExAttack: "",
    Attack: "/image/Tomoe/Tomoe-Attack.webp",
    Pick: "/image/Tomoe/Tomoe-Pick.webp",
    Hide: "/image/Tomoe/Tomoe-Hide.webp",
    HideAttack: "/image/Tomoe/Tomoe-HideAttack.webp",
    HideReload: "/image/Tomoe/Tomoe-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Tomoe/Tomoe-Cafe0.webm",
    Cafe2Webm: "/image/Tomoe/Tomoe-Cafe5.webm",
    ExReload: "",
    Name: "Tomoe",
    Kname: "토모에",
    Ns: "/image/Tomoe/Tomoe-Ns.webp",
  },
  {
    Win: "/image/Mutsuki_New/Mutsuki_New-Win.webp",
    Start: "/image/Mutsuki_New/Mutsuki_New-Start.webp",
    Reload: "/image/Mutsuki_New/Mutsuki_New-Reload.webp",
    Ex: "/image/Mutsuki_New/Mutsuki_New-Ex.webp",
    ExAttack: "",
    Attack: "/image/Mutsuki_New/Mutsuki_New-Attack.webp",
    Pick: "/image/Mutsuki_New/Mutsuki_New-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Mutsuki_New/Mutsuki_New-Cafe0.webm",
    Cafe2Webm: "/image/Mutsuki_New/Mutsuki_New-Cafe5.webm",
    ExReload: "",
    Name: "Mutsuki-New",
    Kname: "무츠키(새해)",
    Ns: "/image/Mutsuki_New/Mutsuki_New-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Serika_New/Serika_New-Start.webp",
    Reload: "",
    Ex: "/image/Serika_New/Serika_New-Ex.webp",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Serika_New/Serika_New-Cafe0.webm",
    Cafe2Webm: "/image/Serika_New/Serika_New-Cafe5.webm",
    ExReload: "",
    Name: "Serika-New",
    Kname: "세리카(새해)",
    Ns: "",
  },
  {
    Win: "/image/Wakamo/Wakamo-Win.webp",
    Start: "/image/Wakamo/Wakamo-Start.webp",
    Reload: "/image/Wakamo/Wakamo-Reload.webp",
    Ex: "/image/Wakamo/Wakamo-Ex.webp",
    ExAttack: "",
    Attack: "/image/Wakamo/Wakamo-Attack.webp",
    Pick: "/image/Wakamo/Wakamo-Pick.webp",
    Hide: "/image/Wakamo/Wakamo-Hide.webp",
    HideAttack: "/image/Wakamo/Wakamo-HideAttack.webp",
    HideReload: "/image/Wakamo/Wakamo-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Wakamo/Wakamo-Cafe0.webm",
    Cafe2Webm: "/image/Wakamo/Wakamo-Cafe5.webm",
    ExReload: "",
    Name: "Wakamo",
    Kname: "와카모",
    Ns: "/image/Wakamo/Wakamo-Ns.webp",
  },
  {
    Win: "/image/Fubuki/Fubuki-Win.webp",
    Start: "/image/Fubuki/Fubuki-Start.webp",
    Reload: "/image/Fubuki/Fubuki-Reload.webp",
    Ex: "/image/Fubuki/Fubuki-Ex.webp",
    ExAttack: "",
    Attack: "/image/Fubuki/Fubuki-Attack.webp",
    Pick: "/image/Fubuki/Fubuki-Pick.webp",
    Hide: "/image/Fubuki/Fubuki-Hide.webp",
    HideAttack: "/image/Fubuki/Fubuki-HideAttack.webp",
    HideReload: "/image/Fubuki/Fubuki-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Fubuki/Fubuki-Cafe0.webm",
    Cafe2Webm: "/image/Fubuki/Fubuki-Cafe5.webm",
    ExReload: "",
    Name: "Fubuki",
    Kname: "후부키",
    Ns: "/image/Fubuki/Fubuki-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Sena/Sena-Start.webp",
    Reload: "",
    Ex: "/image/Sena/Sena-Ex.webp",
    ExAttack: "/image/Sena/Sena-ExAttack.webp",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Sena/Sena-Cafe0.webm",
    Cafe2Webm: "/image/Sena/Sena-Cafe5.webm",
    ExReload: "/image/Sena/Sena-ExReload.webp",
    Name: "Sena",
    Kname: "세나",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Chihiro/Chihiro-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Chihiro/Chihiro-Cafe0.webm",
    Cafe2Webm: "/image/Chihiro/Chihiro-Cafe5.webm",
    ExReload: "",
    Name: "Chihiro",
    Kname: "치히로",
    Ns: "",
  },
  {
    Win: "",
    Start: "",
    Reload: "/image/Hina_Swim/Hina_Swim-Reload.webp",
    Ex: "/image/Hina_Swim/Hina_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Hina_Swim/Hina_Swim-Attack.webp",
    Pick: "/image/Hina_Swim/Hina_Swim-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2Webm: "/image/Hina_Swim/Hina_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Hina-Swim",
    Kname: "히나(수영복)",
    Ns: "/image/Hina_Swim/Hina_Swim-Ns.webp",
  },
  {
    Win: "/image/Mimori/Mimori-Win.webp",
    Start: "/image/Mimori/Mimori-Start.webp",
    Reload: "/image/Mimori/Mimori-Reload.webp",
    Ex: "/image/Mimori/Mimori-Ex.webp",
    ExAttack: "",
    Attack: "/image/Mimori/Mimori-Attack.webp",
    Pick: "/image/Mimori/Mimori-Pick.webp",
    Hide: "/image/Mimori/Mimori-Hide.webp",
    HideAttack: "/image/Mimori/Mimori-HideAttack.webp",
    HideReload: "/image/Mimori/Mimori-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Mimori/Mimori-Cafe0.webm",
    Cafe2Webm: "/image/Mimori/Mimori-Cafe5.webm",
    ExReload: "",
    Name: "Mimori",
    Kname: "미모리",
    Ns: "/image/Mimori/Mimori-Ns.webp",
  },
  {
    Win: "/image/Ui/Ui-Win.webp",
    Start: "/image/Ui/Ui-Start.webp",
    Reload: "/image/Ui/Ui-Reload.webp",
    Ex: "/image/Ui/Ui-Ex.webp",
    ExAttack: "",
    Attack: "/image/Ui/Ui-Attack.webp",
    Pick: "/image/Ui/Ui-Pick.webp",
    Hide: "/image/Ui/Ui-Hide.webp",
    HideAttack: "/image/Ui/Ui-HideAttack.webp",
    HideReload: "/image/Ui/Ui-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Ui/Ui-Cafe0.webm",
    Cafe2Webm: "/image/Ui/Ui-Cafe5.webm",
    ExReload: "",
    Name: "Ui",
    Kname: "우이",
    Ns: "/image/Ui/Ui-Ns.webp",
  },
  /* 61-80 까지 */
  {
    Win: "/image/Hinata/Hinata-Win.webp",
    Start: "/image/Hinata/Hinata-Start.webp",
    Reload: "/image/Hinata/Hinata-Reload.webp",
    Ex: "/image/Hinata/Hinata-Ex.webp",
    ExAttack: "",
    Attack: "/image/Hinata/Hinata-Attack.webp",
    Pick: "/image/Hinata/Hinata-Pick.webp",
    Hide: "/image/Hinata/Hinata-Hide.webp",
    HideAttack: "/image/Hinata/Hinata-HideAttack.webp",
    HideReload: "/image/Hinata/Hinata-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Hinata/Hinata-Cafe0.webm",
    Cafe2Webm: "/image/Hinata/Hinata-Cafe5.webm",
    ExReload: "",
    Name: "Hinata",
    Kname: "히나타",
    Ns: "/image/Hinata/Hinata-Ns.webp",
  },
  {
    Win: "/image/Marina/Marina-Win.webp",
    Start: "/image/Marina/Marina-Start.webp",
    Reload: "/image/Marina/Marina-Reload.webp",
    Ex: "/image/Marina/Marina-Ex.webp",
    ExAttack: "",
    Attack: "/image/Marina/Marina-Attack.webp",
    Pick: "/image/Marina/Marina-Pick.webp",
    Hide: "/image/Marina/Marina-Hide.webp",
    HideAttack: "/image/Marina/Marina-HideAttack.webp",
    HideReload: "/image/Marina/Marina-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Marina/Marina-Cafe0.webm",
    Cafe2Webm: "/image/Marina/Marina-Cafe5.webm",
    ExReload: "",
    Name: "Marina",
    Kname: "마리나",
    Ns: "/image/Marina/Marina-Ns.webp",
  },
  {
    Win: "/image/Miyako/Miyako-Win.webp",
    Start: "/image/Miyako/Miyako-Start.webp",
    Reload: "/image/Miyako/Miyako-Reload.webp",
    Ex: "/image/Miyako/Miyako-Ex.webp",
    ExAttack: "",
    Attack: "/image/Miyako/Miyako-Attack.webp",
    Pick: "/image/Miyako/Miyako-Pick.webp",
    Hide: "/image/Miyako/Miyako-Hide.webp",
    HideAttack: "/image/Miyako/Miyako-HideAttack.webp",
    HideReload: "/image/Miyako/Miyako-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Miyako/Miyako-Cafe0.webm",
    Cafe2Webm: "/image/Miyako/Miyako-Cafe5.webm",
    ExReload: "",
    Name: "Miyako",
    Kname: "미야코",
    Ns: "/image/Miyako/Miyako-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Saki/Saki-Start.webp",
    Reload: "",
    Ex: "/image/Saki/Saki-Ex.webp",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Saki/Saki-Cafe0.webm",
    Cafe2Webm: "/image/Saki/Saki-Cafe5.webm",
    ExReload: "",
    Name: "Saki",
    Kname: "사키",
    Ns: "",
  },
  {
    Win: "/image/Miyu/Miyu-Win.webp",
    Start: "/image/Miyu/Miyu-Start.webp",
    Reload: "/image/Miyu/Miyu-Reload.webp",
    Ex: "/image/Miyu/Miyu-Ex.webp",
    ExAttack: "",
    Attack: "/image/Miyu/Miyu-Attack.webp",
    Pick: "/image/Miyu/Miyu-Pick.webp",
    Hide: "/image/Miyu/Miyu-Hide.webp",
    HideAttack: "/image/Miyu/Miyu-HideAttack.webp",
    HideReload: "/image/Miyu/Miyu-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Miyu/Miyu-Cafe0.webm",
    Cafe2Webm: "/image/Miyu/Miyu-Cafe5.webm",
    ExReload: "",
    Name: "Miyu",
    Kname: "미유",
    Ns: "/image/Miyu/Miyu-Ns.webp",
  },
  {
    Win: "",
    Start: "/image/Kaede/Kaede-Start.webp",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Kaede/Kaede-Cafe0.webm",
    Cafe2Webm: "/image/Kaede/Kaede-Cafe5.webm",
    ExReload: "",
    Name: "Kaede",
    Kname: "카에데",
    Ns: "",
  },
  {
    Win: "",
    Start: "/image/Iroha/Iroha-Start.webp",
    Reload: "",
    Ex: "/image/Iroha/Iroha-Ex.webp",
    ExAttack: "/image/Iroha/Iroha-ExAttack.webp",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Iroha/Iroha-Cafe0.webm",
    Cafe2Webm: "/image/Iroha/Iroha-Cafe5.webm",
    ExReload: "/image/Iroha/Iroha-ExReload.webp",
    Name: "Iroha",
    Kname: "이로하",
    Ns: "",
    ExNs: "/image/Iroha/Iroha-ExNs.webp",
  },
  {
    Win: "/image/Michiru/Michiru-Win.webp",
    Start: "/image/Michiru/Michiru-Start.webp",
    Reload: "/image/Michiru/Michiru-Reload.webp",
    Ex: "/image/Michiru/Michiru-Ex.webp",
    ExAttack: "",
    Attack: "/image/Michiru/Michiru-Attack.webp",
    Pick: "/image/Michiru/Michiru-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "/image/Michiru/Michiru-Obj.webp",
    CafeWebm: "/image/Michiru/Michiru-Cafe0.webm",
    Cafe2Webm: "/image/Michiru/Michiru-Cafe5.webm",
    ExReload: "",
    Name: "Michiru",
    Kname: "미치루",
    Ns: "/image/Michiru/Michiru-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "/image/Michiru/Michiru-Reload2.webp",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Tsukuyo/Tsukuyo-Win.webp",
    Start: "/image/Tsukuyo/Tsukuyo-Start.webp",
    Reload: "/image/Tsukuyo/Tsukuyo-Reload.webp",
    Ex: "/image/Tsukuyo/Tsukuyo-Ex.webp",
    ExAttack: "",
    Attack: "/image/Tsukuyo/Tsukuyo-Attack.webp",
    Pick: "/image/Tsukuyo/Tsukuyo-Pick.webp",
    Hide: "/image/Tsukuyo/Tsukuyo-Hide.webp",
    HideAttack: "/image/Tsukuyo/Tsukuyo-HideAttack.webp",
    HideReload: "/image/Tsukuyo/Tsukuyo-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Tsukuyo/Tsukuyo-Cafe0.webm",
    Cafe2Webm: "/image/Tsukuyo/Tsukuyo-Cafe5.webm",
    ExReload: "",
    Name: "Tsukuyo",
    Kname: "츠쿠요",
    Ns: "/image/Tsukuyo/Tsukuyo-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Atsuko/Atsuko-Win.webp",
    Start: "/image/Atsuko/Atsuko-Start.webp",
    Reload: "/image/Atsuko/Atsuko-Reload.webp",
    Ex: "/image/Atsuko/Atsuko-Ex.webp",
    ExAttack: "",
    Attack: "/image/Atsuko/Atsuko-Attack.webp",
    Pick: "/image/Atsuko/Atsuko-Pick.webp",
    Hide: "/image/Atsuko/Atsuko-Hide.webp",
    HideAttack: "/image/Atsuko/Atsuko-HideAttack.webp",
    HideReload: "/image/Atsuko/Atsuko-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Atsuko/Atsuko-Cafe0.webm",
    Cafe2Webm: "/image/Atsuko/Atsuko-Cafe5.webm",
    ExReload: "",
    Name: "Atsuko",
    Kname: "아츠코",
    Ns: "/image/Atsuko/Atsuko-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Wakamo_Swim/Wakamo_Swim-Win.webp",
    Start: "/image/Wakamo_Swim/Wakamo_Swim-Start.webp",
    Reload: "/image/Wakamo_Swim/Wakamo_Swim-Reload.webp",
    Ex: "/image/Wakamo_Swim/Wakamo_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Wakamo_Swim/Wakamo_Swim-Attack.webp",
    Pick: "/image/Wakamo_Swim/Wakamo_Swim-Pick.webp",
    Hide: "/image/Wakamo_Swim/Wakamo_Swim-Hide.webp",
    HideAttack: "/image/Wakamo_Swim/Wakamo_Swim-HideAttack.webp",
    HideReload: "/image/Wakamo_Swim/Wakamo_Swim-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Wakamo_Swim/Wakamo_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Wakamo_Swim/Wakamo_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Wakamo-Swim",
    Kname: "와카모(수영복)",
    Ns: "/image/Wakamo_Swim/Wakamo_Swim-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Nonomi_Swim/Nonomi_Swim-Win.webp",
    Start: "/image/Nonomi_Swim/Nonomi_Swim-Start.webp",
    Reload: "/image/Nonomi_Swim/Nonomi_Swim-Reload.webp",
    Ex: "/image/Nonomi_Swim/Nonomi_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Nonomi_Swim/Nonomi_Swim-Attack.webp",
    Pick: "/image/Nonomi_Swim/Nonomi_Swim-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Nonomi_Swim/Nonomi_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Nonomi_Swim/Nonomi_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Nonomi-Swim",
    Kname: "노노미(수영복)",
    Ns: "/image/Nonomi_Swim/Nonomi_Swim-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "",
    Start: "/image/Ayane_Swim/Ayane_Swim-Start.webp",
    Reload: "",
    Ex: "/image/Ayane_Swim/Ayane_Swim-Ex.webp",
    ExAttack: "/image/Ayane_Swim/Ayane_Swim-ExAttack.webp",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Ayane_Swim/Ayane_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Ayane_Swim/Ayane_Swim-Cafe5.webm",
    ExReload: "/image/Ayane_Swim/Ayane_Swim-ExReload.webp",
    Name: "Ayane-Swim",
    Kname: "아야네(수영복)",
    Ns: "",
    ExNs: "/image/Ayane_Swim/Ayane_Swim-ExNs.webp",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Hoshino_Swim/Hoshino_Swim-Win.webp",
    Start: "/image/Hoshino_Swim/Hoshino_Swim-Start.webp",
    Reload: "/image/Hoshino_Swim/Hoshino_Swim-Reload.webp",
    Ex: "/image/Hoshino_Swim/Hoshino_Swim-Ex.webp",
    ExAttack: "/image/Hoshino_Swim/Hoshino_Swim-ExAttack.webp",
    Attack: "/image/Hoshino_Swim/Hoshino_Swim-Attack.webp",
    Pick: "/image/Hoshino_Swim/Hoshino_Swim-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Hoshino_Swim/Hoshino_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Hoshino_Swim/Hoshino_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Hoshino-Swim",
    Kname: "호시노(수영복)",
    Ns: "/image/Hoshino_Swim/Hoshino_Swim-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "",
    Start: "/image/Shizuko_Swim/Shizuko_Swim-Start.webp",
    Reload: "",
    Ex: "/image/Shizuko_Swim/Shizuko_Swim-Ex.webp",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Shizuko_Swim/Shizuko_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Shizuko_Swim/Shizuko_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Shizuko-Swim",
    Kname: "시즈코(수영복)",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Izuna_Swim/Izuna_Swim-Win.webp",
    Start: "/image/Izuna_Swim/Izuna_Swim-Start.webp",
    Reload: "/image/Izuna_Swim/Izuna_Swim-Reload.webp",
    Ex: "/image/Izuna_Swim/Izuna_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Izuna_Swim/Izuna_Swim-Attack.webp",
    Pick: "/image/Izuna_Swim/Izuna_Swim-Pick.webp",
    Hide: "/image/Izuna_Swim/Izuna_Swim-Hide.webp",
    HideAttack: "/image/Izuna_Swim/Izuna_Swim-HideAttack.webp",
    HideReload: "/image/Izuna_Swim/Izuna_Swim-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Izuna_Swim/Izuna_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Izuna_Swim/Izuna_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Izuna-Swim",
    Kname: "이즈나(수영복)",
    Ns: "/image/Izuna_Swim/Izuna_Swim-Ns.webp",
    ExNs: "",
    HideReload2: "/image/Izuna_Swim/Izuna_Swim-HideReload2.webp",
    Reload2: "/image/Izuna_Swim/Izuna_Swim-Reload2.webp",
    Start2: "/image/Izuna_Swim/Izuna_Swim-Start2.webp",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Chise_Swim/Chise_Swim-Win.webp",
    Start: "/image/Chise_Swim/Chise_Swim-Start.webp",
    Reload: "/image/Chise_Swim/Chise_Swim-Reload.webp",
    Ex: "/image/Chise_Swim/Chise_Swim-Ex.webp",
    ExAttack: "",
    Attack: "/image/Chise_Swim/Chise_Swim-Attack.webp",
    Pick: "/image/Chise_Swim/Chise_Swim-Pick.webp",
    Hide: "/image/Chise_Swim/Chise_Swim-Hide.webp",
    HideAttack: "/image/Chise_Swim/Chise_Swim-HideAttack.webp",
    HideReload: "/image/Chise_Swim/Chise_Swim-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Chise_Swim/Chise_Swim-Cafe0.webm",
    Cafe2Webm: "/image/Chise_Swim/Chise_Swim-Cafe5.webm",
    ExReload: "",
    Name: "Chise-Swim",
    Kname: "치세(수영복)",
    Ns: "/image/Chise_Swim/Chise_Swim-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Saori/Saori-Win.webp",
    Start: "/image/Saori/Saori-Start.webp",
    Reload: "/image/Saori/Saori-Reload.webp",
    Ex: "/image/Saori/Saori-Ex.webp",
    ExAttack: "",
    Attack: "/image/Saori/Saori-Attack.webp",
    Pick: "/image/Saori/Saori-Pick.webp",
    Hide: "/image/Saori/Saori-Hide.webp",
    HideAttack: "/image/Saori/Saori-HideAttack.webp",
    HideReload: "/image/Saori/Saori-HideReload.webp",
    Object: "",
    CafeWebm: "/image/Saori/Saori-Cafe0.webm",
    Cafe2Webm: "/image/Saori/Saori-Cafe5.webm",
    ExReload: "",
    Name: "Saori",
    Kname: "사오리",
    Ns: "/image/Saori/Saori-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "",
    Start: "/image/Moe/Moe-Start.webp",
    Reload: "",
    Ex: "/image/Moe/Moe-Ex.webp",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Moe/Moe-Cafe0.webm",
    Cafe2Webm: "/image/Moe/Moe-Cafe5.webm",
    ExReload: "",
    Name: "Moe",
    Kname: "모에",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "/image/Kazusa/Kazusa-Win.webp",
    Start: "/image/Kazusa/Kazusa-Start.webp",
    Reload: "/image/Kazusa/Kazusa-Reload.webp",
    Ex: "/image/Kazusa/Kazusa-Ex.webp",
    ExAttack: "",
    Attack: "/image/Kazusa/Kazusa-Attack.webp",
    Pick: "/image/Kazusa/Kazusa-Pick.webp",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    CafeWebm: "/image/Kazusa/Kazusa-Cafe0.webm",
    Cafe2Webm: "/image/Kazusa/Kazusa-Cafe5.webm",
    ExReload: "",
    Name: "Kazusa",
    Kname: "카즈사",
    Ns: "/image/Kazusa/Kazusa-Ns.webp",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  /* 81-100 까지 */
];
