export const localDB121_140 = [
  {
    _id: { $oid: "65770f5c3f8b0c87fe9d70df" },
    Win: "https://drive.google.com/uc?export=view&id=18TfW_gM42wVY0Tu25WAeRu9gHil5tfpf",
    Start:
      "https://drive.google.com/uc?export=view&id=1fytqJxUy4NwnLImgeppZzexwpyGHLJWM",
    Reload:
      "https://drive.google.com/uc?export=view&id=1ycNpMnmuaIY0Mv8-ZiO1kXcV45cZkaj2",
    Ex: "https://drive.google.com/uc?export=view&id=1U-qBurPdSflP9tw5RAUqwxOZXb6B7Lmi",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1HgEqq1na6yXv7z4e3pfY66j7skLHgrh_",
    Pick: "https://drive.google.com/uc?export=view&id=1nevnrAGhBXYcGBJdbHqRR9KR93b6oRat",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1lfEqDoYoupf5PF1Nde5y7Kd6mhNwtcYt",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1mCtycP-ZiXH21nINmJ58dA3jbiQLVMXV",
    ExReload: "",
    Name: "Aris-Maid",
    Kname: "아리스(메이드)",
    Ns: "https://drive.google.com/uc?export=view&id=11qllDLHmIHuH_wFNbDfUCgna1Aprin5s",
    ExNs: "",
    HideReload2: "",
    Reload2:
      "https://drive.google.com/uc?export=view&id=1Pvm1M0MBFWCvYy_KQVdBga7BMhvJ4zf2",
    Start2:
      "https://drive.google.com/uc?export=view&id=1-1EeY_nYSIQrZC8SWyaw90JehZ9uyqyA",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770fe93f8b0c87fe9d70e0" },
    Win: "https://drive.google.com/uc?export=view&id=1aqdn6htPPlZpp_3qNCorslnRVx0_Y7ix",
    Start:
      "https://drive.google.com/uc?export=view&id=1z-MAULpqQVvG0EHhDqAYCgb9zLZb3Pt_",
    Reload:
      "https://drive.google.com/uc?export=view&id=1T0CL8CqYucbOwfy1HXtfrb-qv4JFmupW",
    Ex: "https://drive.google.com/uc?export=view&id=1I9bsc2QAbMT1MULpSTtGQwbXYp8xKWcX",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1nt1pRKZ1dKGLYXGu1YQ-q412huPnsqOP",
    Pick: "https://drive.google.com/uc?export=view&id=1rPqnnP4XszZ4qFuispqZNYAh_WpL6iM_",
    Hide: "https://drive.google.com/uc?export=view&id=1iiLJVs-5dg2CkzE3ZCBuBi31lcK9qOtS",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1flogDBqzrqMfAMw-imI8Veb4cyRetRAm",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1fve8OTb9nQ1w7cd7FQ-WtZb7ZEDg85vw",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1DdQUKQaS7IKQXoc7uyTbNTLmn8-cqlpx",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1JgKgoRc_-PGYjeEsbaJomLRE0wKbhAcs",
    ExReload: "",
    Name: "Toki-Bunny",
    Kname: "토키(바니걸)",
    Ns: "https://drive.google.com/uc?export=view&id=1YpJJbTLRUVXNz71YMBDzmbX2RvRBuhiK",
    ExNs: "",
    HideReload2:
      "https://drive.google.com/uc?export=view&id=1j0FM_NbVKIQFX7YVSGeHR9LMxIqBxqGg",
    Reload2:
      "https://drive.google.com/uc?export=view&id=1fw10bneGdqdl6_Ow7ka_-2rehoe7RUmt",
    Start2:
      "https://drive.google.com/uc?export=view&id=1YS2pQubLMRZ24xWoiN70SAZtL2qVTbXi",
    Cafe3: "",
    Ex2: "",
    Win2: "https://drive.google.com/uc?export=view&id=1fvHk9Z4obGYEorSkhGeFO96zqPT7EjQ-",
  },
  {
    _id: { $oid: "657710a63f8b0c87fe9d70e1" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1BSge1oCNbEmYnEiolOFG1k7coxN3hkKJ",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1UktbkcsGmZ0s7Ep2OIn0wWkIlHNFompc",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1D2hdnRU0CuIvLg26r_5aOFJfUwaFBxoR",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1yP1f-4-q8-cLZPYMLatbo_2PM7VdC7YV",
    ExReload: "",
    Name: "Yuzu-Maid",
    Kname: "유즈(메이드)",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657710da3f8b0c87fe9d70e2" },
    Win: "https://drive.google.com/uc?export=view&id=1mt0Ww2h-NPDQDsF2T4WbkLnBI3ByXOb8",
    Start:
      "https://drive.google.com/uc?export=view&id=1jxNCvbgKThant3u1Fq52UYVPI-vuDZ7r",
    Reload:
      "https://drive.google.com/uc?export=view&id=1QYdXXAANWyr9ialyUbMwvtpZ5ByXmCNt",
    Ex: "https://drive.google.com/uc?export=view&id=10IUYwjF5sbmbYZVx9cSiggiIgLvoJQCM",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1MBArj2ONQVM0Za_eMGemK5zUs4CXtytV",
    Pick: "https://drive.google.com/uc?export=view&id=1IM1wgaMz7pllmABwUMXVfGO1wodFT5Bs",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=17jWBrE0GimGcypDa66vbrzfa-SiVCmeb",
    Cafe2: "",
    ExReload: "",
    Name: "Reisa",
    Kname: "레이사",
    Ns: "https://drive.google.com/uc?export=view&id=1k8iOUnw-tC-JuOHJXIYTJD5e2p_zMHfS",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2:
      "https://drive.google.com/uc?export=view&id=1lE2-S6zp7iDk-vSDMigeAyoxrHkbS479",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6577113d3f8b0c87fe9d70e3" },
    Win: "https://drive.google.com/uc?export=view&id=1HfDp81ci2q-ej-F31RgwDxRXmqacJkPu",
    Start:
      "https://drive.google.com/uc?export=view&id=1W4GCOXU5myOFgaIG7StvKo_T-PkoddTn",
    Reload:
      "https://drive.google.com/uc?export=view&id=1c-XMyh6XrZY89X_MMPxgqzoo4NlyvfBX",
    Ex: "https://drive.google.com/uc?export=view&id=1Qpqv3JTvHUFZ8M9lH3hHbSqcCoeTrZmn",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1ZYm_Kubqy2ChvFL7hXtu5myYsGVH_Gq4",
    Pick: "https://drive.google.com/uc?export=view&id=1vNdrYTPoDQGrja8JZtw7MibFxCTTcHLN",
    Hide: "https://drive.google.com/uc?export=view&id=1T4B1rVCbb3TIkFj0Mj-l9iuPgLEu-hen",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1Dh5ES_H5_rcBdZjd5xfyKB7aZa46qYY2",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1z9sVhwsbKcm9aERG6eXLC7rHhwXuDFEV",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1ozCXpz2hy3IgObDW46r7TbLNt9w5e3_P",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1fMxc--cLtMA9K5PMgPDKQR8OlC19vQNN",
    ExReload: "",
    Name: "Rumi",
    Kname: "루미",
    Ns: "https://drive.google.com/uc?export=view&id=1hl2Evjxgaf8OFSi5uXKYEBXc4H5NLegB",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  /* 5개 */
  {
    _id: { $oid: "657711a83f8b0c87fe9d70e4" },
    Win: "https://drive.google.com/uc?export=view&id=1vBd7rZDObCSa97it_COUfkvyxjW2wWss",
    Start:
      "https://drive.google.com/uc?export=view&id=1RdpK0u2ofoD7Z3BxCrfv2c65Uh8gGZAs",
    Reload:
      "https://drive.google.com/uc?export=view&id=1cgenTq53AZPpZpT9vArCqsj1Y8ZmWZ3n",
    Ex: "https://drive.google.com/uc?export=view&id=1kQfnE02nVKCFNpYMZkLmj-g5NP9T3nNO",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1Tvzz65BqigOT8B1Lcy0zE_HNqJhGFbId",
    Pick: "https://drive.google.com/uc?export=view&id=1A31lkPK4KN__Z1doY80my6MaS0N3MBqA",
    Hide: "https://drive.google.com/uc?export=view&id=1I5qcDKYnzeeqUseVXlGDgJcKWdWGbKzG",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1Gm4olVjkevWsOx_zKvVEMQCjyRCR_N4t",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1DwjLmhmTbq6F1IqqxHhmg_BNvPdw_Ke6",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1dBgN8BZmW2nPzjWMg1oBfYsbFYFaWeE3",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1ZK9AQmqL1yk-b_yrOBcQd7zsic3xSmjm",
    ExReload: "",
    Name: "Mina",
    Kname: "미나",
    Ns: "https://drive.google.com/uc?export=view&id=1gblCWSevjNQInX4AuTM6sq8E4VQZ0X_J",
    ExNs: "",
    HideReload2: "",
    Reload2:
      "https://drive.google.com/uc?export=view&id=1tZzQUynrbpN28OSwotydXc5m6o2yvFOV",
    Start2:
      "https://drive.google.com/uc?export=view&id=1XZirc-GyWF7UG0lriAAwHu6_Yy3PHvZl",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "https://drive.google.com/uc?export=view&id=1VXSatSMSfP2rO-bwt8agGl60csbDBqPe",
    Start:
      "https://drive.google.com/uc?export=view&id=1FjWYRpils9h2uCTO_CvKrLQEeY9xACxT",
    Reload:
      "https://drive.google.com/uc?export=view&id=1L_d-iCG3r5JVVtp3MR0ZpvTphu5symfh",
    Ex: "https://drive.google.com/uc?export=view&id=1fUKJYB9P3SYEG_RkPCyJKdMflKcOlcEG",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1jbf7wkT9cBuPZdaKfrFpPE4qGZABzfLH",
    Pick: "https://drive.google.com/uc?export=view&id=1Dzz4xcPrjVh92to_tIRAsm_V_gPqSo3d",
    Hide: "https://drive.google.com/uc?export=view&id=1Alk7ywBauFsQX2ijMfNtP-uPrHFJ2yo-",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1AZV7YVQjNrx1c7x2PfhE0wAggtflvkjB",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1h9ZTz9qaIWMWdGzO6UtP61H-uJwrPQPh",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Koharu",
    Kname: "코하루",
    Ns: "https://drive.google.com/uc?export=view&id=1nxWGZk53U9sX1m7ccLy2pCQ-eR13KLZr",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    Win: "",
    Win2: "",
    Start: "",
    Start2: "",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1YxtGFUtbneShoLmvj8TCl358oObEJsmp",
    Cafe3: "",
    Ex: "",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Name: "Hanae-Christmas",
    Kname: "하나에(크리스마스)",
  },
  {
    Win: "",
    Win2: "",
    Start: "",
    Start2: "",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1_v8QF9yRoFENEf74dc14R9QDoiAlxFG2",
    Cafe3: "",
    Ex: "",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Name: "Kaho",
    Kname: "카호",
  },
  {
    Win: "",
    Win2: "",
    Start: "",
    Start2: "",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=137EoFhOIZWwmUMYYp81fuFY5kLT44l4L",
    Cafe3: "",
    Ex: "",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Name: "Koyuki",
    Kname: "코유키",
  },
  /* 10개 */
  {
    Win: "",
    Win2: "",
    Start: "",
    Start2: "",
    Reload: "",
    Reload2: "",
    Attack: "",
    Ns: "",
    Pick: "",
    Object: "",
    Cafe: "",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1v3FD2bruZXyt8Rb9DWUv0B7qTuAy0POm",
    Cafe3: "",
    Ex: "",
    ExAttack: "",
    ExReload: "",
    ExNs: "",
    Ex2: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    HideReload2: "",
    Name: "Noa",
    Kname: "노아",
  },
];
