export const localDB101_120 = [
  {
    _id: { $oid: "6576fef64adc2c8711e5d5f5" },
    Win: "https://drive.google.com/uc?export=view&id=1tIpLEFmwjiVK3tzKdhveR5a5DXeYwMCw",
    Start:
      "https://drive.google.com/uc?export=view&id=1tQjY-VK1PSJi6vd_sKaIsDQ4xwpP6NLP",
    Reload:
      "https://drive.google.com/uc?export=view&id=12F93PwI8AYsSje3t9RK_OBrYJ1zKkXwf",
    Ex: "https://drive.google.com/uc?export=view&id=1K4_VdVFcmDWu9uLqaDZAdFb0PH5pOg3e",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=12rrLdFypk9KNrQkHgPo-M9WcXEetsqYf",
    Pick: "https://drive.google.com/uc?export=view&id=10FZrXFt5qo5tePaPAz-cZbMRnC8HELpW",
    Hide: "https://drive.google.com/uc?export=view&id=1toQu5B_oOq1zHOsodD0qO7zUt1rKj_Xr",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1CXmPDoDWy1uX36okpqzNr2omzWVH9idI",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1KnLyj0OJe5YQSKn0VAgMGvfT1_KLU0YQ",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1Jedv7ibVucy44HQ1Hz4yjYxDSOmHJcwN",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1JkI3ljVKCY6Xzn5fb_6pmD6Jr7aH1dvE",
    ExReload: "",
    Name: "Kokona",
    Kname: "코코나",
    Ns: "https://drive.google.com/uc?export=view&id=1DXgFXewnzuIQTRrTFdIuJdCvBXpYZFvV",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6576ff774adc2c8711e5d5f6" },
    Win: "https://drive.google.com/uc?export=view&id=1QZN7O7vQ8H7B0aa35kCW1aimi7zxK5Dc",
    Start:
      "https://drive.google.com/uc?export=view&id=18SzoVEQLGC5M5Bb5nn2bYjYkvnnSJ-P1",
    Reload:
      "https://drive.google.com/uc?export=view&id=1FEUfhmv29O6O3cs_6YW5EBR_uHmPhJ5V",
    Ex: "https://drive.google.com/uc?export=view&id=1o7VRgrZChE4RSv-xPo0ioRSscdTW0eha",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1MTgmPeC5Q0YqUIU53t0VsQkXfj1uiQlz",
    Pick: "https://drive.google.com/uc?export=view&id=1d_lA4ElEDHTzwGI7DxOEojSD0qbS1cIh",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1GgNknta_KEdBobd8iKph8zKQ6d3P57Sm",
    Cafe2: "",
    ExReload: "",
    Name: "Hibiki-Cheer",
    Kname: "히비키(응원단)",
    Ns: "https://drive.google.com/uc?export=view&id=17dOH77itzcrQzELVjPNoq4TRwaC0OEQs",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657703bf4adc2c8711e5d5f7" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1ro8TcvuFiYq2fjejFEuus0RJQnTbp6AV",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1ue-oQakQEKo1ajj3-OFHj3Wwheg8fa7m",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1BO9Oo9XWl8RFWerwohTmUqfWdexni9Lu",
    ExReload: "",
    Name: "Akane-Bunny",
    Kname: "아카네(바니걸)",
    Ns: "https://drive.google.com/uc?export=view&id=1SQOchAwwUH6UOXccHVXXTlii5rYdgO2L",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "6577043f4adc2c8711e5d5f8" },
    Win: "https://drive.google.com/uc?export=view&id=1VNVijUb1iv7VxDbaE_6AhuwQF4FSpr6d",
    Start:
      "https://drive.google.com/uc?export=view&id=1bGshkBqL21J-84qnTHttlP5TQJXP_TPo",
    Reload:
      "https://drive.google.com/uc?export=view&id=1eSryxomyLHZoBr7N4vaerZAlP6g7aUqY",
    Ex: "https://drive.google.com/uc?export=view&id=1yZ7iQGqiaE9x3eZtRmZbU-B527WFuN9S",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1tUuE-MXc4-1FPHD7lbLVMNuOJoPBWOlz",
    Pick: "https://drive.google.com/uc?export=view&id=1Uq6QJJeQut0HNIZEzjcBjaPIaTp-LXjE",
    Hide: "https://drive.google.com/uc?export=view&id=1D3QWbWvYonmD_6uBI4q7iaDgJNMpY_Ex",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1Z12FL49-16idGgfJlBqLKjw24n7ESr08",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1LcT4BCPlBQhIzIxI7Wlhws4teJekUPqn",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Yuuka-Track",
    Kname: "유우카(체육복)",
    Ns: "https://drive.google.com/uc?export=view&id=1ydIR5gdfrRRtiYL3NCaq2y7ZT_Az5PvU",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657704f44adc2c8711e5d5f9" },
    Win: "https://drive.google.com/uc?export=view&id=1NEX9ulQyIBvRCYFOnskkili8rx4C3kNb",
    Start:
      "https://drive.google.com/uc?export=view&id=1-X2EAp2JDfMvIKdbp45pVDcPXXB6R1UA",
    Reload:
      "https://drive.google.com/uc?export=view&id=16M5AQNCmkUXpJCEkcYsvntkMNB0KC4pw",
    Ex: "https://drive.google.com/uc?export=view&id=19W5OEadVlxKVZ1I_0KQUFj2mc4zo7a_b",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1GhqZzwv2Yl3FhhiCBE-whVEvY56U-GgA",
    Pick: "https://drive.google.com/uc?export=view&id=1wClIYhOSDFQ1dDswYW6UOvGVHjbSO4zc",
    Hide: "https://drive.google.com/uc?export=view&id=17rF30u3CcoaJt5NTurjf-ItEdYcikzos",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1vBPviHGvFXzmCBzjurjAbxCljxw97vFH",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1-bFmVTAodtlW-NHOIQwthEw5Wy21XMJ3",
    Object:
      "https://drive.google.com/uc?export=view&id=14IA33cWo5hKrmFa3yM6ydnbxlfo5zzDn",
    Cafe: "https://drive.google.com/uc?export=view&id=18H_mvXkkvoScGi3rB4UESMbpTlFJw_IE",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1U2dTwALxPxcPUUkJzMM2BO1RF4wMZzcy",
    ExReload: "",
    Name: "Mari-Track",
    Kname: "마리(체육복)",
    Ns: "https://drive.google.com/uc?export=view&id=1InFSk0mXhSLT9zNk53FFLQqOJXcr2OFz",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657707103f8b0c87fe9d70d0" },
    Win: "https://drive.google.com/uc?export=view&id=1oiAfbzsrFqHItFe7EZTT8_UTU7qjocb9",
    Start:
      "https://drive.google.com/uc?export=view&id=14_rjd-9EY8iNWPxcTt_kZX3NdqMMpMo7",
    Reload:
      "https://drive.google.com/uc?export=view&id=1Dk8NY2i-IlVyRXxGIBNHsnDv1Uqnx5EI",
    Ex: "https://drive.google.com/uc?export=view&id=1EEcX_UudoNW9cmXavCMvWdPyQkJeQDyG",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1x5fzjuXdUi5BJaVavQN8ClL6oJ9wSAr7",
    Pick: "https://drive.google.com/uc?export=view&id=1HyKSZQCa0FdKBrrpwUbnv0e1Ulph3d-k",
    Hide: "https://drive.google.com/uc?export=view&id=1arNxnCQy2-bvSAHYQ2V0ne8KqrRC8OQN",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=18qR6nPu9NkQMuakX_GwvrxD3BeiFkAY_",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1f1nPiqmxnGIi30I4PIZeL-KhO5olv8Zu",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1yYtkWwFLQWV1ODQAw63hBXHoeNApOscV",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1ZlTQWK25_XHpyJy00LkNb5ppvRiO__oh",
    ExReload: "",
    Name: "Hasumi-Track",
    Kname: "하스미(체육복)",
    Ns: "https://drive.google.com/uc?export=view&id=1oRK1dWZ0jSpXxC0Stlrrbb_lpfZbYcuq",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657707ab3f8b0c87fe9d70d1" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=151ULk73ttrw0IEg_y9yVAUIS8CO_dgAs",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=151_IAa2zk74P8U0ZDSyXnha6tjajLqfz",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=165BVuf-MenFsFNXkPEJ7fs1oAsBsKdqf",
    ExReload: "",
    Name: "Himari",
    Kname: "히마리",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657707cb3f8b0c87fe9d70d2" },
    Win: "https://drive.google.com/uc?export=view&id=1bZFUZFzqsy6uSuJ9lbW0zjBA4viCR1Bc",
    Start:
      "https://drive.google.com/uc?export=view&id=1eQCrlfG_YUdq-QeSYaoyMfzYckBqwIM5",
    Reload:
      "https://drive.google.com/uc?export=view&id=1TP3iVPv_znQeKzhIyAfI05VdmAZ9IihM",
    Ex: "https://drive.google.com/uc?export=view&id=1PWcFqCCLqtSgG9ZXkjPOpmYJ_xuPccgp",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1-olzvYMJVv9wJQ3bIkmB2QIDCQKOP6qJ",
    Pick: "https://drive.google.com/uc?export=view&id=1kLCNeG-yZM8ft8gVheWnGLjzNTQfT3cu",
    Hide: "https://drive.google.com/uc?export=view&id=19EnmB4gypVJx1XyVzMhod8WMIQ96YIdI",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1Zm7Cqrhpy9QsCt8oGVVtWTIgU7PHSduW",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1x0lY77_KUAxPt1nfm1jYONJ7a1FdXrIr",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1qEr40tgWJnYLgp5syrPOvKwTXyJh2Y0z",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1o5wDS-zaE5q6ONUOWbMju4PczNQo5h2g",
    ExReload: "",
    Name: "Shigure",
    Kname: "시구레",
    Ns: "https://drive.google.com/uc?export=view&id=1wqKBKHN-ZZL0EvkOGS7IkNelHlelqLos",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657708db3f8b0c87fe9d70d3" },
    Win: "https://drive.google.com/uc?export=view&id=1PLmXiYQk8m-WpX7VduNzI7z2c9kfYMkz",
    Start:
      "https://drive.google.com/uc?export=view&id=1AFowff6IZ0yLEGpae_HbSpbArzZbpAlS",
    Reload:
      "https://drive.google.com/uc?export=view&id=1TFw2Ppw1vyXvyG0Rv7OGtxrMvkanETsU",
    Ex: "https://drive.google.com/uc?export=view&id=1b_RJ3wBeVGgnnQahFpXWx3sNyUK6v4i4",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1qYl_w7FnTwe3ch27pKiFGzYZRc0G2LZS",
    Pick: "https://drive.google.com/uc?export=view&id=1SoM9m2X1iYg3UUR7yLl9BsPPJxWCMD6N",
    Hide: "https://drive.google.com/uc?export=view&id=1IL4xFq5_qolfPSdezSnRW-AbFU93WgVL",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1_5M64z5XUlxwouNqt3B4t_Caizkkg1fC",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1sHyBiJbs8MUhkLfg-xatBxLLjFZcPy7v",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1jZfoauzFepRd6BVWFdHgQ5qj2f0fD__y",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1UBm0eoSlFPfNvDOrv9tc3izif59GqBL8",
    ExReload: "",
    Name: "Serina-Christmas",
    Kname: "세리나(크리스마스)",
    Ns: "https://drive.google.com/uc?export=view&id=1Rp5U0D63LpNZz3qFu71ZRb8paNKj0PNk",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "657709603f8b0c87fe9d70d4" },
    Win: "https://drive.google.com/uc?export=view&id=1JgFFG6KlOnunHdHUxshQxrHTeTaMmNHI",
    Start:
      "https://drive.google.com/uc?export=view&id=1g52_wUwxgKujFWKn2iF6UshbYIMcjj4J",
    Reload:
      "https://drive.google.com/uc?export=view&id=1hj_rs5D1QuAAqbWkMXC1c09-ecUGG-EA",
    Ex: "https://drive.google.com/uc?export=view&id=1wSLelO3b1g28HZhTND_uSq_Pplji9IAL",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1OsNL1A0RhnO0EFkwLGCkW4g_z1gnx6ZV",
    Pick: "https://drive.google.com/uc?export=view&id=1KtEvN4yUppyzvBhhYYldugY5UAw9lYJ1",
    Hide: "https://drive.google.com/uc?export=view&id=1FvttMS4qD3yyGFHODaAMl1_5qG-_pJ-X",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1rE4MoXLOluUeycd4pmSir0d04-IcHiPJ",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1HYlRuSsoNjtgadP-UINs5VhPXMdtK1SE",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1Rwq4Uvs7IArDshe0EJoas1FpIcdzPdoI",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1hI-_G7elo2-pEBDl3IgM41s_Qn0FLt0S",
    ExReload: "",
    Name: "Haruna-New",
    Kname: "하루나(새해)",
    Ns: "https://drive.google.com/uc?export=view&id=1gS6waqoVfjsgAsH1rM9sFNSrYZAVFQXi",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770a7d3f8b0c87fe9d70d5" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1MWBordZyCualU_Uz-KsYX5CHA2RJBAtR",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1NSbOJvD580leumgKtVwbuM-GmX5wj2i8",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1bv1kazt5HMw8_oRqUVu83RB53ngxZ8uv",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1bYN7D6KS-1fVXH7kAEiUqk5a3t-xb9Su",
    ExReload: "",
    Name: "Fuuka-New",
    Kname: "후우카(새해)",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770ad23f8b0c87fe9d70d6" },
    Win: "https://drive.google.com/uc?export=view&id=1ZDmpGbInwxacFn6HUogLbLxnnH6UmXaT",
    Start:
      "https://drive.google.com/uc?export=view&id=1H6JwUw_dQmOYNugQKdSIG8tM6K8K8Qpd",
    Reload:
      "https://drive.google.com/uc?export=view&id=1iZp-0hjN9Plgbu4nDK1i9apJD2FhJePS",
    Ex: "https://drive.google.com/uc?export=view&id=1kkwNF_7UAQpsXYBB6mEyFsfvAXYwCNrD",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1SfDgLzdWFz722eFsYBelcRkbeUa1l2wI",
    Pick: "https://drive.google.com/uc?export=view&id=1pPoVYmmtSgbRLcUPdPQIbHCcXpeCprnu",
    Hide: "https://drive.google.com/uc?export=view&id=1Cs68dIl-0-7Y1usY3_zRLD6q4JcHqq5k",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=14alZ-Og7rBW5RVap8Yja1Bj1yeETqLuN",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1pqBnEf8x0enFkKujgWWhyEQLKpSBK7B3",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1iFIYfwl-4ayqaZfxET4IXP_EWss-fNBd",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1AKDjPnRGbn-A11_D03IBZEyId4OeqyrQ",
    ExReload: "",
    Name: "Junko-New",
    Kname: "준코(새해)",
    Ns: "https://drive.google.com/uc?export=view&id=1_qV_ADFnVDWj8CeXCT2vBHyuKwDLcCIa",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770bdb3f8b0c87fe9d70d7" },
    Win: "https://drive.google.com/uc?export=view&id=1qGDM3g2WL4UM-Aucti6hgWhfuoA3EZpp",
    Start:
      "https://drive.google.com/uc?export=view&id=16myzqZdWBVgIomp9nlzX49pEtLMwm1OZ",
    Reload:
      "https://drive.google.com/uc?export=view&id=1KteX0dvUHzr0wjx88G38NuhXSfVgFnHU",
    Ex: "https://drive.google.com/uc?export=view&id=1qZrjXCMri3SL-Lhy-0vBCoPka17jW4uv",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1yYqrYDhSlfE5myzFnSnLoSunAtKNS1t-",
    Pick: "https://drive.google.com/uc?export=view&id=1PTmlFb3xrlDm-0-rFprSSRKOXEF8uAQc",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1PVZ22tB_4u5CRf7bQ0UoWPm1rrt-gGFI",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1Ic5E6Fd2pV4NbIiyow6KAntMXxPvL0R0",
    ExReload: "",
    Name: "Mine",
    Kname: "미네",
    Ns: "https://drive.google.com/uc?export=view&id=15x5LvL8F0x6v8MY_juIYpnLxkgtK0QRv",
    ExNs: "",
    HideReload2: "",
    Reload2:
      "https://drive.google.com/uc?export=view&id=14W_DOjLDvbXddZLErHyCb1ZhH1tegRAt",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770c4d3f8b0c87fe9d70d8" },
    Win: "https://drive.google.com/uc?export=view&id=1eYxzDFfKnH9nkHDaFoC0fyROeg-_p7fz",
    Start:
      "https://drive.google.com/uc?export=view&id=1B5yDF2RDXQOnpHAWyenuWGOZ_C3kIuVi",
    Reload:
      "https://drive.google.com/uc?export=view&id=15cQ5rL4tCZ-H8BfOhnA7pCq-hQ1F001H",
    Ex: "https://drive.google.com/uc?export=view&id=1--emV4DB_zmdehjnTrgNJJowkPXSQslL",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1JFuAg_SL02wWL4Z6oHOuDS-NFb9vGVOD",
    Pick: "https://drive.google.com/uc?export=view&id=1dS9Zrap2a6DnQOv2KIYqLze6imam5ETO",
    Hide: "https://drive.google.com/uc?export=view&id=1ravsfdNcXOrAoQSDa4_gySoBhxxyP5Vh",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1nsxgr2z4uwGzgcrjjlqR6nnKdHUek4jr",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1pKzXRqh8oue1qfVSjANu0MRxDng6KXzz",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1S2Aodv7tvsGTn-sqoTfKap-Q9TA8ccWu",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1VGNwzc-ZieYZMz7zxoeghCQ-vYLY7DLo",
    ExReload: "",
    Name: "Mika",
    Kname: "미카",
    Ns: "https://drive.google.com/uc?export=view&id=1AhWIILOUJv52AmWAAem1MYPiboTZlDrz",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770cd13f8b0c87fe9d70d9" },
    Win: "https://drive.google.com/uc?export=view&id=1N7nWP7mcoUYxPR8ta3EcbxqzM9o-ZVmr",
    Start:
      "https://drive.google.com/uc?export=view&id=1xHN_sZxAuq8efZxjvjtrZId8wXwe5EQj",
    Reload:
      "https://drive.google.com/uc?export=view&id=18qOgTs7eFSoZNX8HiwSNBS5LXUpocv9a",
    Ex: "https://drive.google.com/uc?export=view&id=12QQ-tLOiNft1nR-cOzCsEZKmHnE4Mggt",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1t9NbgMbJw0p166-UP0Dx71HA5Ng8Zdcp",
    Pick: "https://drive.google.com/uc?export=view&id=1xzv85iTvf4v6Td3TeCVAIjVJFe15B7JV",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1GuZyC-Dev9tjPtZCSgKzHkAXpgOX5wYr",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1FAlHO6vC1_4Zt5ZLyoz_ioS4gnJ_pAXH",
    ExReload: "",
    Name: "Megu",
    Kname: "메구",
    Ns: "https://drive.google.com/uc?export=view&id=11ZfOdiYCH9YSVzuhvYnlC3DKMrR7ORpw",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770d363f8b0c87fe9d70da" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1sFxx_i2jtXRtg_d83k6xhiorh4UFTQP4",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1-OGXcI8pONdmktlFejs9Sk39bPg1jCoG",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1G9trhjFcI4t5Aa_ow5ua7518Qp_PDMIO",
    ExReload: "",
    Name: "Kanna",
    Kname: "칸나",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770d5d3f8b0c87fe9d70db" },
    Win: "https://drive.google.com/uc?export=view&id=1SU-RU8WIWRaNVxg6Ka9922DgK1xDDsZv",
    Start:
      "https://drive.google.com/uc?export=view&id=13Lbh1oK26QLM8NWnIDSqOCOR3ZVSser9",
    Reload:
      "https://drive.google.com/uc?export=view&id=1VXX225_44vOXm34ZZ3eyfajUuVvK0HNG",
    Ex: "https://drive.google.com/uc?export=view&id=1ta3O4Fr1lAgyijfQRVr2_2B0-keEYZgM",
    ExAttack:
      "https://drive.google.com/uc?export=view&id=1JZUbsoI0vXvw9ovjnbVBifJ12iCP-iqG",
    Attack:
      "https://drive.google.com/uc?export=view&id=1RupcvDAPRHaGZISReGgVndXC734LyqrM",
    Pick: "https://drive.google.com/uc?export=view&id=10oRwpMrjV-SkYaLqp1PYPqYff4piKltW",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1YZE8tDILcp8CCBWNPT1nFX8IEqcY0fWt",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1E2xGLrz8iaC5xvVkBbJH0X1JanZ91Oj2",
    ExReload:
      "https://drive.google.com/uc?export=view&id=1bqFlT6qHIv5Z96nxMq__TptBXtY7YVJY",
    Name: "Toki",
    Kname: "토키",
    Ns: "https://drive.google.com/uc?export=view&id=1I4IjWrBt62mAhgbdUADvMGVNTfOYa3yT",
    ExNs: "https://drive.google.com/uc?export=view&id=1Iygdxo5NPJDiPuPZorDy1FFJIhl7G4rD",
    HideReload2: "",
    Reload2: "",
    Start2:
      "https://drive.google.com/uc?export=view&id=1x-9WE1VfEyN9RunM9wu9pK5QZCFKnRav",
    Cafe3: "",
    Ex2: "https://drive.google.com/uc?export=view&id=1mZOCaGe0MT5qZRTXoTCvhBrN8hngxTpD",
    Win2: "https://drive.google.com/uc?export=view&id=1TunntnMO_k6iMCCQm1MpqUAxMrL3Mas1",
  },
  {
    _id: { $oid: "65770e4f3f8b0c87fe9d70dc" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1KUKuuOC1Wqx_rIifm7M-5gzdBEWjJZkS",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1B_Oe_OBwgD7Aavv36WJ57HUyoACSw3Sh",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1zymK2URTzYeXSr_EG8S1Fb_EY_kpns4D",
    ExReload: "",
    Name: "Nagisa",
    Kname: "나기사",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770e8d3f8b0c87fe9d70dd" },
    Win: "https://drive.google.com/uc?export=view&id=1WJ-7O5TD7E4aRhCvU5RO9vUcgEwrMc_2",
    Start:
      "https://drive.google.com/uc?export=view&id=1xL8IFCVrigCtNFlPk2z2mILHcU9eqIRr",
    Reload:
      "https://drive.google.com/uc?export=view&id=1rDW5Z97iTs8z9BlLyDy-Bv7P3wkbwgRk",
    Ex: "https://drive.google.com/uc?export=view&id=1cwl-IDk7-VJ7GxN-950xInU8FEK0Svf0",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1phLQsv9728mZFQaWCqXisWDxluuwIasZ",
    Pick: "https://drive.google.com/uc?export=view&id=1de6ZW0PoIlw8A-9ZUbB5S-fAf4ZDbUOF",
    Hide: "https://drive.google.com/uc?export=view&id=1__qfQo9piCpdH3lrT_Hb4VhpnGsfv6F-",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=1TUpFbCHIWdG9Pd6I_uSO_oZuK5HOupt2",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1VXlLY3hkCONGK1RNwGqoNsW9l4LJVij1",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=19aYKi-4bxo7yBMWKPopW4t81-3KRqour",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1zh5rwuBI3NFUzYy8g8bR_2Whpr3oBZFZ",
    ExReload: "",
    Name: "Kayoko-New",
    Kname: "카요코(새해)",
    Ns: "https://drive.google.com/uc?export=view&id=1Hrj5-v4npva1E0Ea7ydt91w6nEDE9Wfh",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2:
      "https://drive.google.com/uc?export=view&id=1Pfx5IcC-psfEj4cd28qy698n3ozMCCZk",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
  {
    _id: { $oid: "65770f253f8b0c87fe9d70de" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1Qb7K0B1Wm1SWof1T4XO0qIif0Msblqrq",
    Reload: "",
    Ex: "https://drive.google.com/uc?export=view&id=1uAJWcpXaxAye-XVbXajfJMWX1lSuCqcH",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Haruka-New",
    Kname: "하루카(새해)",
    Ns: "",
    ExNs: "",
    HideReload2: "",
    Reload2: "",
    Start2: "",
    Cafe3: "",
    Ex2: "",
    Win2: "",
  },
];
