export const localDB21_40 = [
  {
    _id: { $oid: "656dadea61d6d3405971b206" },
    Win: "https://drive.google.com/uc?export=view&id=1OcqRqke2FrgACfiajboOPGJ-LnNEqBcG",
    Start:
      "https://drive.google.com/uc?export=view&id=1C9CaeJY8fA83GLbApiTRXlgK7fWBpd0E",
    Reload:
      "https://drive.google.com/uc?export=view&id=1u7ZGRtjampWrDuAG0J8XE4WfogQkF7w3",
    Ex: "https://drive.google.com/uc?export=view&id=16X_6_PXG2FkNUjJk-ftkti6BQaG0PP7f",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1IUTFk7mJCkj6iJg8a2LgE69Ar7ApFnJg",
    Pick: "https://drive.google.com/uc?export=view&id=1Dfiji8MsazAoc0PSjOx3ZRjJJwdpS6EZ",
    Hide: "https://drive.google.com/uc?export=view&id=1-AfRVUam8uE8FbbvXmPtvZVl8M42l2B-",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=10XR4CxyV7xWO04b19dT3VpjqHQfFVqAn",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1UfalwHhDPEqnq0KU_HIKLBbQlj6JK9zf",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1YpYTLeLKsqpr3TwtSdUzNzen7WPtifRl",
    Cafe2: "",
    ExReload: "",
    Name: "Kayoko",
    Kname: "카요코",
    Ns: "https://drive.google.com/uc?export=view&id=1uFF60h7MvIBax4N0OGQc0vdE4Wgl9KDn",
  },
  {
    _id: { $oid: "656e7bba86953509454d128f" },
    Win: "https://drive.google.com/uc?export=view&id=1_9eI8-VIHeHx6hCpfX_hOfvrsoQCEkcC",
    Start:
      "https://drive.google.com/uc?export=view&id=1O_3pyTLcWc-sLun7DauAISiJvpolfF2f",
    Reload:
      "https://drive.google.com/uc?export=view&id=16q9IUlYtITfy8LVLEfpVsWtdY5wXGsjR",
    Ex: "https://drive.google.com/uc?export=view&id=1_0Ibto0XVQRAcmY2tMX3aAWpI0sl-kbO",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1jQoLCJNXGYbCXvp1cfX1mrdSyBjz9QBk",
    Pick: "https://drive.google.com/uc?export=view&id=152Vgf6pJvCDnmTnK8U4XnfCZ1QIckSQE",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1NzDQ5TsMocH0-E-Sxi1QtPlXA94uHHFI",
    Cafe2: "",
    ExReload: "",
    Name: "Mutsuki",
    Kname: "무츠키",
    Ns: "https://drive.google.com/uc?export=view&id=1AaV8oX3YDzWF-EJEBxVkM-n74gvWeok-",
  },
  {
    _id: { $oid: "656e854a86953509454d1290" },
    Win: "https://drive.google.com/uc?export=view&id=1s0wD6KQGmBOXXTTX_OZ4nzgiCF53MEV7",
    Start:
      "https://drive.google.com/uc?export=view&id=1PGtK_bpPT3N6JE2DKKTBIGfzbEa6uTnX",
    Reload:
      "https://drive.google.com/uc?export=view&id=1idTC_YhoQevtRqyWT6X9e_JxJBwGXP-H",
    Ex: "https://drive.google.com/uc?export=view&id=1S1RUPrSbZxg-CHGXj3yHBoowD8MYjfv6",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1dkhDhXWIqQKgQTtM_SgQ3yfKJBxdKFeZ",
    Pick: "https://drive.google.com/uc?export=view&id=193thREx5eUTSFlfKISQsGN1Wko8-NEnB",
    Hide: "https://drive.google.com/uc?export=view&id=1yKBbOuRYeLUrxbBTIUi-1ldS8xhWToek",
    HideAttack: "",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1pIBkwqzoYHu7vQV8gablgPsHau5GY1Uq",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=17GVZ8IBuMgm80VhJ5CUXylcZta-0TEJx",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1YdGkPkO83ajb6BIUZFvgXRS12gN0_X8G",
    ExReload: "",
    Name: "Junko",
    Kname: "준코",
    Ns: "https://drive.google.com/uc?export=view&id=1tgIE5FCJ3pRPG_sc6mXxQ0Fns2EipKmT",
  },
  {
    _id: { $oid: "656e937a86953509454d1291" },
    Win: "https://drive.google.com/uc?export=view&id=1U5qvUkOp9D1NXoXTkOoPEVrBo2NPjlxM",
    Start:
      "https://drive.google.com/uc?export=view&id=1s8LDyOgpIv8hrp178cG82kcmUPKWjoJw",
    Reload:
      "https://drive.google.com/uc?export=view&id=1VulZlfibZnPLRVdxVD2g8_3dCLuXwyLD",
    Ex: "https://drive.google.com/uc?export=view&id=1m1xIRIYP6zGgQgKD_uEuKuxaJTnX7ekj",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1E_A0U_Rfyn6z0bIEVkCu55A6xxEVnlCH",
    Pick: "https://drive.google.com/uc?export=view&id=1kH7PKij81Wy9yml1rGu9bSh9n4KIw18Y",
    Hide: "https://drive.google.com/uc?export=view&id=1lL3grP_pMcR0YCYRZ5LcBhjrzKG53nch",
    HideAttack: "",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1652N2NmBBAwIw8H7j1MwTfNTFSQuzcUJ",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1oV2W8phAeBodHZLiZ_R7Tk-477q4mtP_",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1Q-brBZtqBxOTBiYAmwnO-F1we_TfJIAJ",
    ExReload: "",
    Name: "Serika",
    Kname: "세리카",
    Ns: "https://drive.google.com/uc?export=view&id=1aHQnJCuaVFfgYk76fZXEub3me25vHpVe",
  },
  {
    _id: { $oid: "656e982786953509454d1292" },
    Win: "https://drive.google.com/uc?export=view&id=15FtjxHIthk0fSubLkvRaVGrHSL9nPdjQ",
    Start:
      "https://drive.google.com/uc?export=view&id=1UAMwSdlxVsWrZi63yAwHSAhEAzlNh759",
    Reload:
      "https://drive.google.com/uc?export=view&id=1FwBISm8zoDIp4oXZsuxL7-TeXrT43OWK",
    Ex: "https://drive.google.com/uc?export=view&id=17jfXNXx3xcCLnBbR6JsAiVT3SuucBh4Z",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1fMm2DiIkbkqerGOPvLmxyLZr7NqnWme0",
    Pick: "https://drive.google.com/uc?export=view&id=1eY9CZ7FEG84PNRraxQSguBgamS5kdUS0",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1aa8_dPg-YSQ63WfnchXAW1C2OMcMhkr1",
    Cafe2: "",
    ExReload: "",
    Name: "Tsubaki",
    Kname: "츠바키",
    Ns: "https://drive.google.com/uc?export=view&id=1lNfx8XKs1pLaUGVNvFLLqcjFEWX68wZT",
  },
  {
    _id: { $oid: "656f031f3f92ca4c6aae707b" },
    Win: "https://drive.google.com/uc?export=view&id=1YkOdK6GX54aK_5ACZwCM1vM8lwnTqApt",
    Start:
      "https://drive.google.com/uc?export=view&id=1R6lojETx0sjk3jO_qMpbma5e4wCfQYW3",
    Reload:
      "https://drive.google.com/uc?export=view&id=1tq-knF3h7sVXp_23v1a7xqoYThrs0Gap",
    Ex: "https://drive.google.com/uc?export=view&id=1XmKCo6_vRjnvyJRR-HFCDqL7-hVOTUqW",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1Ad96I0-_vysKhMrmkR23P3mmAoxgVWtB",
    Pick: "https://drive.google.com/uc?export=view&id=1xIRRTnzZgP1zUtNMXqFoippib-zqcqzQ",
    Hide: "https://drive.google.com/uc?export=view&id=1Oz8JDlHHPtdC6CQVjhX-ADZmg7E8191n",
    HideAttack:
      "https://drive.google.com/uc?export=view&id=12vi7xkL7zm2own9BWRe_akKaViCGw0IG",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1iVyOZymcOg1E_IEPvVRQmZo5A-hz_r0O",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Yuuka",
    Kname: "유우카",
    Ns: "https://drive.google.com/uc?export=view&id=12Tfhiywr7BVX-keOCdWENyaRH024RtGs",
  },
  {
    _id: { $oid: "656f08793f92ca4c6aae707c" },
    Win: "https://drive.google.com/uc?export=view&id=1zTMThHlEZyElF9Nd57qA56PfeZZqj1CV",
    Start:
      "https://drive.google.com/uc?export=view&id=1hNuMGogYOkVsJ1rjvEM6zvbtjsYBTXSj",
    Reload:
      "https://drive.google.com/uc?export=view&id=1BBlUI9iXItckMWpKDpWM5HNRqng7RQDF",
    Ex: "https://drive.google.com/uc?export=view&id=1zQ0Yr3y2-bmNBBS8ze10IIB8qRUDPCzN",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1BnrIPsVUucK3wyD1prtJ-Ad0CJjg03q-",
    Pick: "https://drive.google.com/uc?export=view&id=1z6ByQh278XvwbHUrIKTXvrEjbsGiY18J",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1bG7q9xP61yJjuQlXBs57AQrIqECsO_fe",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1_-Y7VDt5y_vAS5K_D2wLlJofOsqxD5hu",
    ExReload: "",
    Name: "Haruka",
    Kname: "하루카",
    Ns: "https://drive.google.com/uc?export=view&id=1tI-xKVmaoS9zvumt8hSDWVKEUsyImBOI",
  },
  {
    _id: { $oid: "656f114e3f92ca4c6aae707d" },
    Win: "https://drive.google.com/uc?export=view&id=17aXwSy4Afr94rVqs6Q96rNOTQbBysXmh",
    Start:
      "https://drive.google.com/uc?export=view&id=1OjS0DeyI5AcGZJk4SjVK8OKXyH6DIAQm",
    Reload:
      "https://drive.google.com/uc?export=view&id=1wyyiemDQm6OwptMtfDZ5L6NUiTibMpBq",
    Ex: "https://drive.google.com/uc?export=view&id=1qWJ5coSMl0e12TlKbkCgCutaRyK9SySg",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=14bwe9_sGbDK30iqr6NiE06ZFOfWXtvEx",
    Pick: "https://drive.google.com/uc?export=view&id=1_CXIiFvparyvRd71WyALLHa-EKhROot1",
    Hide: "https://drive.google.com/uc?export=view&id=16cdamsD6pcfsA6dZFGTwn-t1YKVfBYe3",
    HideAttack: "",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1gRPG-VCm2ygQqN-CziQdHKMl0nBZcHwc",
    Object: "",
    Cafe: "",
    Cafe2: "",
    ExReload: "",
    Name: "Asuna",
    Kname: "아스나",
    Ns: "https://drive.google.com/uc?export=view&id=1qgInsjHFgzbwpv-Zt693NQ4VZ8MvXK-h",
  },
  {
    _id: { $oid: "656f15c23f92ca4c6aae707e" },
    Win: "https://drive.google.com/uc?export=view&id=1_fPxKi7e3otXspr5AOEDHdX1kaS4yevu",
    Start:
      "https://drive.google.com/uc?export=view&id=1Yu8tEo3J_h89jr8pCkQIG_TlE449dKCe",
    Reload:
      "https://drive.google.com/uc?export=view&id=1MCp3yPw6Foz0xrMr7EN5-ybWiY2CmqKO",
    Ex: "https://drive.google.com/uc?export=view&id=1M0CbNDCWWUcyRPw60IPESeRNsc101u8Y",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1NIcIZq4glrHyJoiQqMqagBWLkZCbdJgW",
    Pick: "https://drive.google.com/uc?export=view&id=1Yx1EVEFJTfVmlbgUTdEkDFP7eCR9wKiX",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1ClNpt714lv49OsIlD9GjZVKRXoP-EDCC",
    Cafe2: "",
    ExReload: "",
    Name: "Kotori",
    Kname: "코토리",
    Ns: "https://drive.google.com/uc?export=view&id=1PZK0ZEMMNdtnC3n0lmDYI80ggSZWUXy1",
  },
  {
    _id: { $oid: "656f30fe117c9b1e3fdde176" },
    Win: "https://drive.google.com/uc?export=view&id=1eXgVsvARNlGVgHsqAQJK_3h8Jcrd1LfA",
    Start:
      "https://drive.google.com/uc?export=view&id=1qSf1RZk1ZkzeQpb9VxYdDT_nRf5YJrQF",
    Reload:
      "https://drive.google.com/uc?export=view&id=1IhhFL8Tj1F1_82TrkZGxS4YPsCUt3CVQ",
    Ex: "https://drive.google.com/uc?export=view&id=1zbcEaCUcaQKsyZg4-UFQ8Ar8fqZRr8S7",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1-_65YknvSO2rCnFlSIBrSBZcoOJbs2hG",
    Pick: "https://drive.google.com/uc?export=view&id=11Ob169IpazWOrJy6wM_U3ZwpF4KVRQQ0",
    Hide: "https://drive.google.com/uc?export=view&id=1YxujhaEq3QJfMJl1y9A2Xcftz7evwymg",
    HideAttack: "",
    HideReload:
      "https://drive.google.com/uc?export=view&id=1niKG87aHA5hLWbkyj9bh-FQvRmGWHkHe",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1cn3tpZFHQBC5pRwkT8eOhBO3Y8Qg4NVP",
    Cafe2: "",
    ExReload: "",
    Name: "Suzumi",
    Kname: "스즈미",
    Ns: "https://drive.google.com/uc?export=view&id=1A2pdkCMtd2IU9QUysJunN4ShqV_s2QR4",
  },
  {
    _id: { $oid: "656f3610117c9b1e3fdde177" },
    Win: "https://drive.google.com/uc?export=view&id=14bWAQ_2SONV1bXm-kWG_VBAeqxDr6rXk",
    Start:
      "https://drive.google.com/uc?export=view&id=1nwh81g3oEd9l7jBj2phpp3xArRxRHGxd",
    Reload:
      "https://drive.google.com/uc?export=view&id=12sWxOtNC5SVfQE0HrrUwj4Xe1qgx94Mt",
    Ex: "https://drive.google.com/uc?export=view&id=1w-zE6a4ayyh27ph09JQxx_VtEJcVHQnt",
    ExAttack: "",
    Attack:
      "https://drive.google.com/uc?export=view&id=1wZ0HUdLay76fzr1k8SwAt2qtu8pfUo_O",
    Pick: "https://drive.google.com/uc?export=view&id=1MVVn6fh1Q7YVY1MaoOGmd0HsJ7Y_vjVr",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1miCLSwOMaPZD556k2m1_o6ELIiAY2yPS",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1KM2kOIK-CwFhyQgOjMwvIUqYHVyXfHfy",
    ExReload: "",
    Name: "Pina",
    Kname: "피나",
    Ns: "https://drive.google.com/uc?export=view&id=1ywLm7jpH5u8Xn9p7B33vK4hzrZTim1_2",
  },
  {
    _id: { $oid: "656f383e117c9b1e3fdde178" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1xsggC6Fr2PiNYLIFkuXMCWs79G79ccn9",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1vjfbijVzaW7AtZJCnwqKv-xJNSlSG6Dd",
    Cafe2: "",
    ExReload: "",
    Name: "Hibiki",
    Kname: "히비키",
    Ns: "",
  },
  {
    _id: { $oid: "656f397d117c9b1e3fdde179" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=10FTr1OAukErzjuRQ36WrBtCuh6Bi9KAn",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1mgEcFMwcMUFoB8D7mHCKTXth5G5FgZ9H",
    Cafe2: "",
    ExReload: "",
    Name: "Karin",
    Kname: "카린",
    Ns: "",
  },
  {
    _id: { $oid: "656fcfcc6a3dd9a4271f5e17" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1P_ldeEDe_FPgtX09MaQvUVqLhVgFY2I2",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1CIuF5IChZxfvZqmZK1FOF21D_zWK7AcS",
    Cafe2: "",
    ExReload: "",
    Name: "Saya",
    Kname: "사야",
    Ns: "",
  },
  {
    _id: { $oid: "656fd13e6a3dd9a4271f5e18" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=15Z8SR9-xa8qWQzfwsFi6LCjeaeu5rI_o",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1E_Y_sUr3AcNa_XTNDIHZ-bkhJbWl3pJK",
    Cafe2:
      "https://drive.google.com/uc?export=view&id=1vPBzHepUL0H1rW64BJxOzyP6WHnV9i0-",
    ExReload: "",
    Name: "Airi",
    Kname: "아이리",
    Ns: "",
  },
  {
    _id: { $oid: "656fd2c46a3dd9a4271f5e19" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1Le8-cksb6Jj5mR7rqTcwkXKI_L3m_Hz5",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1bwCfGYpI4eP73aSJ1dKLR7zrKaZmgFZq",
    Cafe2: "",
    ExReload: "",
    Name: "Fuuka",
    Kname: "후우카",
    Ns: "",
  },

  {
    _id: { $oid: "656fd3e16a3dd9a4271f5e1a" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=13gFvdK81zmjYe2tBY-Znb6VwDj0YidA2",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1zhBBkgi1d6tX6hDj98n2BpRCh4DzdtNh",
    Cafe2: "",
    ExReload: "",
    Name: "Hanae",
    Kname: "하나에",
    Ns: "",
  },
  {
    _id: { $oid: "656fd5ae6a3dd9a4271f5e1b" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1ySc1xMsiC3o7lOtRNkjgTrCuO7NYY3ny",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1MShn8KE3qVxwTElJChK08zRg7_7v4_ET",
    Cafe2: "",
    ExReload: "",
    Name: "Hare",
    Kname: "하레",
    Ns: "",
  },
  {
    _id: { $oid: "656fd6ad6a3dd9a4271f5e1c" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=11_L3pF4ccIQOmWscC1nzVEC0k1KvYy0f",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1n3IRBdX8gZdGOslD8CRSDuPycK1XXJAY",
    Cafe2: "",
    ExReload: "",
    Name: "Utaha",
    Kname: "우타하",
    Ns: "",
  },
  {
    _id: { $oid: "656fd7c76a3dd9a4271f5e1d" },
    Win: "",
    Start:
      "https://drive.google.com/uc?export=view&id=1s0B6N15ciUjEFnDiL-7xe4TQw7JdFyhE",
    Reload: "",
    Ex: "",
    ExAttack: "",
    Attack: "",
    Pick: "",
    Hide: "",
    HideAttack: "",
    HideReload: "",
    Object: "",
    Cafe: "https://drive.google.com/uc?export=view&id=1LQjk95DYss71hNQJOmpqu7aQ9iMm5BYJ",
    Cafe2: "",
    ExReload: "",
    Name: "Ayane",
    Kname: "아야네",
    Ns: "",
  },
];
